"use client";

import { useEffect, useMemo, useState } from "react";
import type { Channel, DashboardSnapshot, PerformanceMetrics } from "@/lib/types";

const channelOptions:Channel[]=["email","voice","linkedin","instagram","x"];
export default function AnalyticsPage(){
 const [state,setState]=useState<DashboardSnapshot|null>(null);const [missionId,setMissionId]=useState("");const [channel,setChannel]=useState<Channel>("linkedin");const [metrics,setMetrics]=useState<PerformanceMetrics>({impressions:0,engagements:0,clicks:0,replies:0,positiveReplies:0,meetings:0,conversions:0});const [busy,setBusy]=useState<string|null>(null);const [notice,setNotice]=useState("Only factual metrics belong here. Dry-run and simulated replies are excluded automatically.");
 async function refresh(){const res=await fetch("/api/state",{cache:"no-store"});const data=await res.json() as DashboardSnapshot;setState(data);if(!missionId&&data.missions[0])setMissionId(data.missions[0].id);}
 useEffect(()=>{void refresh();},[]);
 const events=useMemo(()=>state?.performance.filter(item=>item.missionId===missionId)||[],[state,missionId]);const learning=useMemo(()=>state?.learnings.find(item=>item.missionId===missionId),[state,missionId]);
 function setMetric(key:keyof PerformanceMetrics,value:string){setMetrics(current=>({...current,[key]:Math.max(0,Number(value)||0)}));}
 async function addEvent(){if(!missionId)return;setBusy("event");try{const res=await fetch("/api/analytics/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({missionId,channel,source:"manual",metrics})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Metric ingestion failed");setNotice("Factual metric event recorded in memory. Run a learning pass to update recommendations.");await refresh();}catch(error){setNotice(error instanceof Error?error.message:"Metric ingestion failed");}finally{setBusy(null);}}
 async function learn(){if(!missionId)return;setBusy("learn");try{const res=await fetch("/api/analytics/learn",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({missionId})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Learning failed");setNotice(`Learning pass complete: ${data.report.evidenceEventIds.length} factual events used.`);await refresh();}catch(error){setNotice(error instanceof Error?error.message:"Learning failed");}finally{setBusy(null);}}
 const card={border:"1px solid #242831",background:"#0f1115",borderRadius:12,padding:18} as const;const input={width:"100%",height:40,marginTop:6,background:"#0b0d10",color:"#eee",border:"1px solid #242831",borderRadius:8,padding:"0 9px"} as const;
 return <main style={{maxWidth:1240,margin:"0 auto",padding:"36px 24px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,marginBottom:24}}><div><span className="eyebrow">MARGARYAN DISTRIBUTION / LEARNING</span><h1 style={{fontSize:42,margin:"8px 0 0"}}>Evidence & Learning</h1><p style={{color:"#8f96a3",maxWidth:740,lineHeight:1.55}}>The agent changes distribution priorities only from recorded evidence. The ranking score is an internal prioritization signal, not a claim of causal attribution.</p></div><a href="/autopilot" className="ghost" style={{textDecoration:"none"}}>Autopilot →</a></header>
  <div className="notice"><span/> {notice}</div>
  <section style={{...card,marginBottom:14}}><div className="panelHead"><div><span>MISSION</span><h3>Evidence scope</h3></div><button className="ghost" disabled={!missionId||busy==="learn"} onClick={learn}>{busy==="learn"?"Learning…":"Run learning pass"}</button></div><select value={missionId} onChange={e=>setMissionId(e.target.value)} style={{...input,marginTop:14}}><option value="">Select mission</option>{(state?.missions||[]).map(item=><option key={item.id} value={item.id}>{item.plan.missionName}</option>)}</select></section>
  <section style={{...card,marginBottom:14}}><div className="panelHead"><div><span>MANUAL / PROVIDER BRIDGE</span><h3>Record factual performance</h3></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:9,marginTop:14}}><label><small>CHANNEL</small><select value={channel} onChange={e=>setChannel(e.target.value as Channel)} style={input}>{channelOptions.map(item=><option key={item}>{item}</option>)}</select></label>{(["impressions","engagements","clicks","replies","positiveReplies","meetings","conversions"] as Array<keyof PerformanceMetrics>).map(key=><label key={key}><small>{key.toUpperCase()}</small><input type="number" min={0} value={metrics[key]||0} onChange={e=>setMetric(key,e.target.value)} style={input}/></label>)}</div><div style={{display:"flex",justifyContent:"flex-end",marginTop:10}}><button className="ghost" disabled={!missionId||busy==="event"} onClick={addEvent}>{busy==="event"?"Recording…":"Record event"}</button></div></section>
  <section style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14,marginBottom:14}}><div style={card}><div className="panelHead"><div><span>CHANNEL RANKING</span><h3>Downstream signals</h3></div></div>{!learning&&<div className="empty">Run a learning pass after factual events arrive.</div>}{learning?.channelRankings.map((item,index)=><div key={item.key} style={{display:"grid",gridTemplateColumns:"32px 1fr auto",gap:10,padding:"12px 4px",borderBottom:"1px solid #1b1e25",alignItems:"center"}}><b style={{color:"#6f7680"}}>#{index+1}</b><div><strong style={{fontSize:12,textTransform:"uppercase"}}>{item.key}</strong><small style={{display:"block",color:"#7d8490",marginTop:4}}>replies {item.replies} · positive {item.positiveReplies} · meetings {item.meetings}</small></div><span style={{fontSize:12,color:"#d8ff62"}}>{item.score}</span></div>)}</div><div style={card}><div className="panelHead"><div><span>PILLAR RANKING</span><h3>What themes earn downstream signal</h3></div></div>{!learning?.pillarRankings.length&&<div className="empty">Content-linked provider metrics will populate pillar learning.</div>}{learning?.pillarRankings.map((item,index)=><div key={item.key} style={{display:"grid",gridTemplateColumns:"32px 1fr auto",gap:10,padding:"12px 4px",borderBottom:"1px solid #1b1e25",alignItems:"center"}}><b style={{color:"#6f7680"}}>#{index+1}</b><strong style={{fontSize:12}}>{item.key}</strong><span style={{fontSize:12,color:"#d8ff62"}}>{item.score}</span></div>)}</div></section>
  <section style={{...card,marginBottom:14}}><div className="panelHead"><div><span>LATEST LEARNING</span><h3>Next experiments</h3></div></div>{learning?<><p style={{color:"#c3c8d0",fontSize:13,lineHeight:1.6}}>{learning.summary}</p><ol style={{color:"#959da8",fontSize:12,lineHeight:1.7}}>{learning.recommendations.map(item=><li key={item}>{item}</li>)}</ol><small style={{color:"#666e79"}}>Evidence events: {learning.evidenceEventIds.length}</small></>:<div className="empty">No learning report yet.</div>}</section>
  <section style={card}><div className="panelHead"><div><span>RAW EVIDENCE</span><h3>{events.length} events</h3></div></div>{events.length===0&&<div className="empty">No factual performance events recorded.</div>}{events.slice(0,30).map(event=><div key={event.id} style={{display:"grid",gridTemplateColumns:"100px 110px 1fr 150px",gap:10,padding:"11px 4px",borderBottom:"1px solid #1b1e25",fontSize:11}}><strong>{event.channel.toUpperCase()}</strong><span style={{color:"#7f8791"}}>{event.source}</span><span style={{color:"#aab0b8"}}>{JSON.stringify(event.metrics)}</span><span style={{color:"#707783"}}>{new Date(event.occurredAt).toLocaleString()}</span></div>)}</section>
 </main>;
}
