import { distributionStore } from "@/lib/store";
import type { BrandVoice, ProductRecord } from "@/lib/types";

type ProductSeed=Omit<ProductRecord,"id"|"createdAt"|"updatedAt">;
const forbiddenClaims=["Do not invent customers, revenue, adoption, accuracy, ROI, integrations or performance numbers.","Do not claim guaranteed rankings, returns, leads, sales or business outcomes.","Do not imply a provider partnership unless an official partnership is documented."];
function voice(tone:string[],avoid:string[],cta:string):BrandVoice{return{tone,writingRules:["Use verifiable product facts and explicit evidence.","Keep claims proportional to the available proof.",cta],avoid,visualDirection:["Product-led","Clear information hierarchy","No fake customer or performance badges"],channelRules:{x:["Lead with one concrete idea"],linkedin:["Prefer evidence, use cases and operator insight"],instagram:["Keep copy concise and visual-first"],email:["Personalize the reason for contact and use one clear CTA"],voice:["Disclose AI representation where required and respect opt-out controls"]}};}

const promptenceSalesMotion={
 primaryGoal:"Win qualified paid Promptence customers and build a repeatable evidence-led sales motion.",
 minimumLeadScore:68,
 segments:[
  {id:"agency",label:"SEO / GEO / AEO / growth agencies",description:"Agencies that can use Promptence for their own positioning and as a measurement layer for client work.",priority:"P0" as const,buyerRoles:["Founder","Managing Director","Head of SEO","Head of Growth","Strategy Director"],fitSignals:["Public SEO, GEO, AEO, AI search or content strategy services","Multiple B2B clients or visible case-study motion","Publishes about AI search, LLM visibility or organic acquisition"],disqualifiers:["No active website or no professional services evidence","Pure consumer agency with no search/content/brand strategy fit"]},
  {id:"b2b_saas",label:"B2B SaaS with active demand generation",description:"Software companies competing for high-intent category queries where AI recommendations can influence evaluation.",priority:"P0" as const,buyerRoles:["VP Marketing","Head of Growth","Head of Demand Generation","SEO Lead","CMO"],fitSignals:["Clear category pages and buyer-intent content","Active SEO/content program","Competitive category with multiple vendors","Public evidence of AI-search or organic growth interest"],disqualifiers:["Pre-launch product with no public demand engine","No identifiable marketing owner or commercial website"]},
  {id:"multi_location",label:"Multi-location and local-service brands",description:"Businesses where AI and local recommendation surfaces can influence discovery across locations.",priority:"P1" as const,buyerRoles:["CMO","Head of Growth","Digital Marketing Director","Marketing Operations"],fitSignals:["Multiple locations or service areas","Strong dependence on discovery/recommendation traffic","Active local SEO or reputation program"],disqualifiers:["Single small location with no growth team unless inbound intent is explicit"]},
  {id:"enterprise_brand",label:"Enterprise / category brands",description:"Larger brands with reputation, category visibility and cross-provider measurement needs.",priority:"P1" as const,buyerRoles:["VP Digital","Head of Organic Growth","Brand Strategy Lead","Marketing Intelligence"],fitSignals:["Large content footprint","Multiple product/category lines","Material brand-recommendation exposure across AI systems"],disqualifiers:["No reachable buyer role and no evidence of an owned search/content program"]}
 ],
 triggerSignals:["Mentions GEO, AEO, AI search, LLM visibility or AI recommendations publicly","Hiring or investing in SEO/content/growth","Runs comparison/category pages where AI recommendation visibility matters","Agency sells SEO/content/PR services to B2B clients","Competitors are visibly discussed in AI-search context"],
 qualificationRules:["Prefer explicit evidence over inferred pain","Require at least one reachable official business channel before sequence execution","Do not score an account above 80 without a concrete trigger signal or strong category-fit evidence","Use source URLs for every material fit statement","Disqualify accounts where Promptence cannot plausibly affect a measurable acquisition or brand-discovery workflow"],
 discoveryQuestions:["Which buyer-intent questions matter most to your pipeline?","Do you currently measure how ChatGPT, Gemini, Claude or Perplexity describe and recommend you?","Which competitors appear when buyers ask AI for category recommendations?","Who owns SEO, content and AI-search visibility internally?","Would a before/after evidence layer be useful for proving changes to leadership or clients?"],
 offers:[
  {code:"free_signal",name:"Free AI visibility signal",priceUsd:0,buyer:"Cold or lightly qualified prospect",whenToUse:"Low-friction first proof when the buyer has not yet confirmed a problem.",cta:"Offer a concrete free signal for the company or category."},
  {code:"managed_diagnostic_1500",name:"AI Visibility Diagnostic",priceUsd:1500,buyer:"Qualified buyer who needs a baseline and diagnosis",whenToUse:"There is a real visibility problem or competitive question but implementation scope is not yet proven.",cta:"Propose a scoped paid diagnostic with evidence and prioritized findings."},
  {code:"managed_sprint_3500",name:"AI Visibility Remediation Sprint",priceUsd:3500,buyer:"Buyer with verified structural or authority gaps",whenToUse:"The diagnostic or public evidence shows multiple changes are required and the buyer wants implementation support.",cta:"Propose an implementation sprint with controlled remeasurement."},
  {code:"managed_infrastructure_7500",name:"AI Visibility & Revenue Infrastructure",priceUsd:7500,buyer:"Larger team needing ongoing integration, governance and measurement",whenToUse:"The account has multiple brands, markets, teams or evidence sources and needs a durable operating layer.",cta:"Propose a scoped infrastructure conversation."},
  {code:"self_serve_monitor",name:"Monitor",priceUsd:39,buyer:"Small team ready for self-serve monitoring",whenToUse:"The buyer wants lightweight recurring tracking rather than managed work.",cta:"Point to the self-serve Monitor plan."},
  {code:"self_serve_growth",name:"Growth",priceUsd:129,buyer:"Growth team needing broader recurring measurements",whenToUse:"The buyer wants broader buyer-intent coverage and evidence history.",cta:"Point to the Growth plan."},
  {code:"self_serve_pro",name:"Pro",priceUsd:349,buyer:"Team needing intervention workflow and larger coverage",whenToUse:"The buyer needs larger query coverage, approvals and controlled remeasurement.",cta:"Point to the Pro plan."}
 ],
 sequenceRules:["Lead with a company-specific observation or question, not a generic product pitch","Sell the next logical commitment, not the entire platform","Use the free signal as a proof mechanism, not as fake urgency","Move to paid Diagnostic when a real problem is confirmed","Move to Sprint only after evidence shows implementation work","Use voice only after interest or where compliant voice-first outreach is explicitly approved","Stop immediately on opt-out or clear negative intent"],
 successDefinition:["Qualified positive replies","Booked meetings with a relevant buyer","Paid Diagnostic","Paid Remediation Sprint","Recurring self-serve or monitoring subscription","Verified revenue event rather than simulated pipeline"]
};

export const PORTFOLIO_PRODUCTS:ProductSeed[]=[
{name:"Promptence",sourceUrl:"https://promptence.tech",notes:"Margaryan Labs product and the first internal customer of Margaryan Distribution. Use the live Promptence site, current repository truth and this sales motion before every campaign.",language:"en",oneLiner:"Outcome-oriented AI visibility intelligence: measure how brands appear in AI answers, identify evidence gaps, implement approved changes and verify the before/after delta.",targetCustomer:"SEO/GEO/AEO agencies, B2B SaaS growth teams, multi-location brands and enterprise marketing teams that need evidence of how AI systems describe, cite and recommend them.",pains:["No reliable baseline for AI recommendation visibility","Competitors appear in buyer-intent AI answers without a measurable response plan","SEO/content teams cannot prove which interventions changed AI visibility","Agencies need a repeatable evidence layer for client AI-search work"],proof:["Promptence provides a free AI visibility signal before subscription.","Current production catalog includes Monitor at $39/month, Growth at $129/month and Pro at $349/month.","Current managed offers include AI Visibility Diagnostic at $1,500, Remediation Sprint at $3,500 and AI Visibility & Revenue Infrastructure at $7,500.","Promptence architecture separates measured evidence from manual assumptions and supports controlled remeasurement after approved changes."],pricingNotes:"Current public self-serve: Free signal, Monitor $39/month, Growth $129/month, Pro $349/month. Managed: Diagnostic $1,500, Remediation Sprint $3,500, Infrastructure $7,500. Never invent discounts or enterprise pricing.",forbiddenClaims,positioning:["Evidence before promises","AI recommendation visibility tied to buyer-intent questions","Source-level proof and competitor context","Approved remediation with before/after remeasurement","Commercial motion from free signal to paid diagnostic to implementation and monitoring"],objections:["AI outputs vary over time, so Promptence uses repeated measurements and remeasurement rather than one screenshot","Buyers may confuse AI visibility with traditional SEO; position Promptence as an additional evidence and decision layer","Prospects may expect guaranteed ranking or revenue; never promise either"],useCases:["Free AI visibility signal","Competitive AI visibility baseline","Agency client diagnostic","Managed AI Visibility Diagnostic","Remediation Sprint","Ongoing Monitor / Growth / Pro measurement","Before/after evidence for executive or client reporting"],salesMotion:promptenceSalesMotion,brandVoice:voice(["Evidence-first","Calm","Precise","Commercial","Operator-led"],["hype","guaranteed ranking claims","fabricated proof","generic AI-sales language"],"Use a concrete observation, one proof mechanism and one next-step CTA.")},
{name:"VETO Intelligence",notes:"Trading decision-intelligence product. Pull current capabilities from its repository or approved Product Brain before campaigns.",language:"en",oneLiner:"Decision intelligence for market analysis, risk context and governed trading decisions.",targetCustomer:"Professional traders, research teams and market participants evaluating decision-support infrastructure.",pains:["Fragmented market evidence","Inconsistent decision process","Weak auditability of trading decisions"],proof:[],pricingNotes:"No public price should be invented.",forbiddenClaims:[...forbiddenClaims,"Do not promise investment returns, profitable trades or risk-free outcomes."],positioning:["Decision support, not financial guarantees","Evidence and risk context","Governed decision workflow"],objections:["Financial decisions are high-stakes","Prospects may expect predictions rather than decision support"],useCases:["Market decision support","Risk review","Evidence trace","Decision workflow"],brandVoice:voice(["Institutional","Restrained","Analytical"],["get-rich language","guaranteed predictions","sensational claims"],"Invite a product walkthrough or controlled evaluation.")},
{name:"Meqena",notes:"Automotive marketplace product. Verify current market, deployment and commercial scope before outbound.",language:"en",oneLiner:"Digital automotive marketplace infrastructure for vehicle discovery, dealers and marketplace operations.",targetCustomer:"Automotive marketplace operators, dealer networks and businesses launching or upgrading a vehicle marketplace.",pains:["Fragmented listings","Weak dealer tooling","Poor marketplace UX"],proof:[],pricingNotes:"Use only operator-approved commercial terms.",forbiddenClaims,positioning:["Marketplace infrastructure","Dealer and buyer workflow","Modern automotive commerce experience"],objections:["Marketplace liquidity depends on supply and demand","Local integrations vary by market"],useCases:["Marketplace launch","Dealer onboarding","Vehicle discovery","Marketplace modernization"],brandVoice:voice(["Modern","Practical","Product-led"],["unverified market leadership claims","fake inventory metrics"],"Offer a live product demo or acquisition/licensing conversation.")},
{name:"RAIOS",sourceUrl:"https://raios.pro",notes:"Restaurant intelligence/operations product. Verify current live functionality before every claim.",language:"en",oneLiner:"Restaurant intelligence and operating software for turning operational data into clearer decisions.",targetCustomer:"Restaurant operators, groups and hospitality technology partners.",pains:["Disconnected operating data","Slow operational decisions","Difficulty turning restaurant data into actions"],proof:[],pricingNotes:"Use only current public or operator-approved pricing.",forbiddenClaims,positioning:["Restaurant operating intelligence","Decision support","Operational visibility"],objections:["Restaurant workflows differ by concept and market","Integrations may vary"],useCases:["Operational visibility","Restaurant analytics","Management decision support"],brandVoice:voice(["Operational","Clear","Premium"],["invented ROI","fake restaurant customers"],"Offer a scoped demo or pilot.")},
{name:"INGU",sourceUrl:"https://ingu.shop",notes:"Fashion marketplace/product. Verify current live commerce capabilities and seller availability before campaigns.",language:"en",oneLiner:"Fashion marketplace experience for discovering brands and curated products.",targetCustomer:"Fashion shoppers, independent brands and marketplace partners where the current product supports them.",pains:["Fragmented brand discovery","Weak digital merchandising","Limited marketplace visibility"],proof:[],pricingNotes:"Do not invent seller fees, GMV or commercial terms.",forbiddenClaims,positioning:["Curated fashion discovery","Marketplace experience","Brand presentation"],objections:["Inventory and fulfillment capabilities must be verified","Marketplace scale should never be overstated"],useCases:["Fashion discovery","Brand marketplace presence","Curated commerce"],brandVoice:voice(["Editorial","Minimal","Premium"],["fake scarcity","fake brand partnerships","unverified sales claims"],"Invite exploration, seller interest or partnership only when supported.")}
];

export function ensurePortfolioProducts(){
 const existing=new Map(distributionStore.listProducts().map(item=>[item.name.trim().toLowerCase(),item]));
 const created:ProductRecord[]=[];
 const refreshed:ProductRecord[]=[];
 for(const seed of PORTFOLIO_PRODUCTS){
  const key=seed.name.trim().toLowerCase();
  const current=existing.get(key);
  if(current){
   const updated=distributionStore.updateProduct(current.id,seed);
   if(updated){existing.set(key,updated);refreshed.push(updated);}
   continue;
  }
  const product=distributionStore.addProduct(seed);existing.set(key,product);created.push(product);
 }
 return{created,refreshed,products:distributionStore.listProducts(),catalog:PORTFOLIO_PRODUCTS.map(item=>({name:item.name,sourceUrl:item.sourceUrl||null,oneLiner:item.oneLiner}))};
}
