import { distributionStore } from "@/lib/store";
import type { ProductRecord } from "@/lib/types";

type ProductSeed=Omit<ProductRecord,"id"|"createdAt"|"updatedAt">;
const forbiddenClaims=["Do not invent customers, revenue, adoption, accuracy, ROI, integrations or performance numbers.","Do not claim guaranteed rankings, returns, leads, sales or business outcomes.","Do not imply a provider partnership unless an official partnership is documented."];

export const PORTFOLIO_PRODUCTS:ProductSeed[]=[
{name:"Promptence",sourceUrl:"https://promptence.tech",notes:"Margaryan Labs product. Use the public site and current Product Brain as source of truth before each campaign.",language:"en",oneLiner:"AI visibility measurement and recommendation intelligence for brands and agencies.",targetCustomer:"Brands, growth teams and agencies that need evidence of how companies appear in AI-generated recommendations.",pains:["Unknown visibility across AI answers","Competitors appearing for buyer-intent questions","Difficulty proving before/after change"],proof:["Public methodology and visibility baseline are published on promptence.tech."],pricingNotes:"Use only current pricing published by Promptence or explicitly approved by the operator.",forbiddenClaims,positioning:["Evidence before promises","Provider-specific measurement","Comparable remeasurement after approved changes"],objections:["AI outputs vary over time","Buyers may confuse AI visibility with traditional SEO"],useCases:["AI visibility baseline","Competitive visibility measurement","Agency measurement layer","Before/after remeasurement"],brandVoice:{tone:"Evidence-first, calm, precise, commercial",avoid:["hype","guaranteed ranking claims","fabricated proof"],ctaStyle:"Offer a concrete scan, baseline or partner conversation"}},
{name:"VETO Intelligence",notes:"Trading decision-intelligence product. Pull current capabilities from its repository or approved Product Brain before campaigns.",language:"en",oneLiner:"Decision intelligence for market analysis, risk context and governed trading decisions.",targetCustomer:"Professional traders, research teams and market participants evaluating decision-support infrastructure.",pains:["Fragmented market evidence","Inconsistent decision process","Weak auditability of trading decisions"],proof:[],pricingNotes:"No public price should be invented.",forbiddenClaims:[...forbiddenClaims,"Do not promise investment returns, profitable trades or risk-free outcomes."],positioning:["Decision support, not financial guarantees","Evidence and risk context","Governed decision workflow"],objections:["Financial decisions are high-stakes","Prospects may expect predictions rather than decision support"],useCases:["Market decision support","Risk review","Evidence trace","Decision workflow"],brandVoice:{tone:"Institutional, restrained, analytical",avoid:["get-rich language","guaranteed predictions","sensational claims"],ctaStyle:"Invite a product walkthrough or controlled evaluation"}},
{name:"Meqena",notes:"Automotive marketplace product. Verify current market, deployment and commercial scope before outbound.",language:"en",oneLiner:"Digital automotive marketplace infrastructure for vehicle discovery, dealers and marketplace operations.",targetCustomer:"Automotive marketplace operators, dealer networks and businesses launching or upgrading a vehicle marketplace.",pains:["Fragmented listings","Weak dealer tooling","Poor marketplace UX"],proof:[],pricingNotes:"Use only operator-approved commercial terms.",forbiddenClaims,positioning:["Marketplace infrastructure","Dealer and buyer workflow","Modern automotive commerce experience"],objections:["Marketplace liquidity depends on supply and demand","Local integrations vary by market"],useCases:["Marketplace launch","Dealer onboarding","Vehicle discovery","Marketplace modernization"],brandVoice:{tone:"Modern, practical, product-led",avoid:["unverified market leadership claims","fake inventory metrics"],ctaStyle:"Offer a live product demo or acquisition/licensing conversation"}},
{name:"RAIOS",sourceUrl:"https://raios.pro",notes:"Restaurant intelligence/operations product. Verify current live functionality before every claim.",language:"en",oneLiner:"Restaurant intelligence and operating software for turning operational data into clearer decisions.",targetCustomer:"Restaurant operators, groups and hospitality technology partners.",pains:["Disconnected operating data","Slow operational decisions","Difficulty turning restaurant data into actions"],proof:[],pricingNotes:"Use only current public or operator-approved pricing.",forbiddenClaims,positioning:["Restaurant operating intelligence","Decision support","Operational visibility"],objections:["Restaurant workflows differ by concept and market","Integrations may vary"],useCases:["Operational visibility","Restaurant analytics","Management decision support"],brandVoice:{tone:"Operational, clear, premium",avoid:["invented ROI","fake restaurant customers"],ctaStyle:"Offer a scoped demo or pilot"}},
{name:"INGU",sourceUrl:"https://ingu.shop",notes:"Fashion marketplace/product. Verify current live commerce capabilities and seller availability before campaigns.",language:"en",oneLiner:"Fashion marketplace experience for discovering brands and curated products.",targetCustomer:"Fashion shoppers, independent brands and marketplace partners where the current product supports them.",pains:["Fragmented brand discovery","Weak digital merchandising","Limited marketplace visibility"],proof:[],pricingNotes:"Do not invent seller fees, GMV or commercial terms.",forbiddenClaims,positioning:["Curated fashion discovery","Marketplace experience","Brand presentation"],objections:["Inventory and fulfillment capabilities must be verified","Marketplace scale should never be overstated"],useCases:["Fashion discovery","Brand marketplace presence","Curated commerce"],brandVoice:{tone:"Editorial, minimal, premium",avoid:["fake scarcity","fake brand partnerships","unverified sales claims"],ctaStyle:"Invite exploration, seller interest or partnership only when supported"}}
];

export function ensurePortfolioProducts(){const existing=new Map(distributionStore.listProducts().map(item=>[item.name.trim().toLowerCase(),item]));const created:ProductRecord[]=[];for(const seed of PORTFOLIO_PRODUCTS){const key=seed.name.trim().toLowerCase();if(existing.has(key))continue;const product=distributionStore.addProduct(seed);existing.set(key,product);created.push(product);}return{created,products:distributionStore.listProducts(),catalog:PORTFOLIO_PRODUCTS.map(item=>({name:item.name,sourceUrl:item.sourceUrl||null,oneLiner:item.oneLiner}))};}
