"use client";

import { useEffect, useMemo, useState } from "react";
import type { DashboardSnapshot, MissionRecord } from "@/lib/types";

export default function SmmPage(){
  const [state,setState]=useState<DashboardSnapshot|null>(null);const [missionId,setMissionId]=useState("");const [source,setSource]=useState("");const [busy,setBusy]=useState<string|null>(null);const [notice,setNotice]=useState("Build a scheduled campaign or repurpose one source across channels.");
  async function refresh(){const res=await fetch("/api/state",{cache:"no-store"});const data=await res.json() as DashboardSnapshot;setState(data);if(!missionId&&data.missions[0])setMissionId(data.missions[0].id);}
  useEffect(()=>{void refresh();},[]);
  const mission=useMemo(()=>state?.missions.find(item=>item.id===missionId),[state,missionId]);const drafts=useMemo(()=>state?.content.filter(item=>item.missionId===missionId)||[],[state,missionId]);
  async function buildCampaign(){if(!missionId)return;setBusy("campaign");try{const res=await fetch("/api/content/campaign",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({missionId,days:7})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Campaign failed");setNotice(`Created ${data.drafts.length} drafts and ${data.queued.length} scheduled actions.`);await refresh();}catch(error){setNotice(error instanceof Error?error.message:"Campaign failed");}finally{setBusy(null);}}
  async function repurpose(){if(!missionId||!source.trim())return;setBusy("repurpose");try{const res=await fetch("/api/content/repurpose",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({missionId,sourceText:source})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Repurpose failed");setNotice(`Repurposed source into ${data.drafts.length} channel-native drafts.`);await refresh();}catch(error){setNotice(error instanceof Error?error.message:"Repurpose failed");}finally{setBusy(null);}}
  const card={border:"1px solid #242831",background:"#0f1115",borderRadius:12,padding:18} as const;
  return <main style={{maxWidth:1280,margin:"0 auto",padding:"36px 24px 70px"}}>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,marginBottom:24}}><div><span className="eyebrow">MARGARYAN DISTRIBUTION / SMM</span><h1 style={{fontSize:42,margin:"8px 0 0"}}>SMM Operations</h1></div><a href="/" className="ghost" style={{textDecoration:"none"}}>← Command Center</a></header>
    <div className="notice"><span/> {notice}</div>
    <section style={{...card,marginBottom:14}}><div className="panelHead"><div><span>ACTIVE MISSION</span><h3>Campaign context</h3></div></div><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:12,alignItems:"end",marginTop:16}}><label><span style={{fontSize:9,color:"#777",letterSpacing:1.5}}>MISSION</span><select value={missionId} onChange={e=>setMissionId(e.target.value)} style={{display:"block",width:"100%",marginTop:7,height:42,background:"#0b0d10",color:"#eee",border:"1px solid #242831",borderRadius:8,padding:"0 10px"}}><option value="">Select mission</option>{(state?.missions||[]).map((item:MissionRecord)=><option key={item.id} value={item.id}>{item.plan.missionName}</option>)}</select></label><button className="ghost" onClick={buildCampaign} disabled={!missionId||busy==="campaign"}>{busy==="campaign"?"Building…":"Build 7-day campaign"}</button></div>{mission&&<p style={{color:"#8f96a3",fontSize:12,lineHeight:1.6,margin:"14px 0 0"}}>{mission.plan.thesis}</p>}</section>
    <section style={{...card,marginBottom:14}}><div className="panelHead"><div><span>REPURPOSE ENGINE</span><h3>One source → multiple channels</h3></div></div><textarea value={source} onChange={e=>setSource(e.target.value)} placeholder="Paste a launch note, product update, founder idea, transcript excerpt or case-study text…" style={{width:"100%",minHeight:150,marginTop:16,background:"#0b0d10",color:"#eee",border:"1px solid #242831",borderRadius:9,padding:14,resize:"vertical"}}/><div style={{display:"flex",justifyContent:"flex-end",marginTop:10}}><button className="ghost" onClick={repurpose} disabled={!missionId||!source.trim()||busy==="repurpose"}>{busy==="repurpose"?"Repurposing…":"Repurpose source"}</button></div></section>
    <section style={card}><div className="panelHead"><div><span>CONTENT CALENDAR</span><h3>{drafts.length} generated assets</h3></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:10,marginTop:14}}>{drafts.length===0&&<div className="empty">No content for this mission yet.</div>}{drafts.map(item=><article key={item.id} style={{border:"1px solid #1b1e25",background:"#0b0d10",borderRadius:10,padding:15}}><div style={{display:"flex",justifyContent:"space-between",gap:8,fontSize:9,color:"#89909b",textTransform:"uppercase"}}><span>{item.channel} · {item.format||"post"}</span><span>{item.scheduledAt?new Date(item.scheduledAt).toLocaleString():"draft"}</span></div><h4 style={{margin:"14px 0 8px",fontSize:14}}>{item.title}</h4><p style={{whiteSpace:"pre-wrap",color:"#9aa1ac",fontSize:12,lineHeight:1.55}}>{item.body}</p>{item.callToAction&&<small style={{display:"block",borderTop:"1px solid #1b1e25",paddingTop:10,color:"#c8d19e"}}>{item.callToAction}</small>}{item.requiresMedia&&<div style={{marginTop:10,fontSize:9,color:"#e8c57a"}}>MEDIA REQUIRED BEFORE PUBLISH</div>}</article>)}</div></section>
  </main>;
}
