import { NextResponse } from "next/server";
import { runPortfolioDirector, type PortfolioDirectorOptions } from "@/lib/agent/portfolio-director";
import { storageRuntime, withDurableState } from "@/lib/store/checkpoint";

function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i+=1)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
function cronAuthorized(req:Request){const secret=process.env.CRON_SECRET;if(!secret)return false;const authorization=req.headers.get("authorization")||"";return safeEqual(authorization,`Bearer ${secret}`);}
function operatorAuthorized(req:Request){const candidates=[process.env.AUTOPILOT_SECRET,process.env.WORKER_SECRET].filter((value):value is string=>Boolean(value));if(!candidates.length)return false;const supplied=[req.headers.get("x-autopilot-secret"),req.headers.get("x-worker-secret")].filter((value):value is string=>Boolean(value));return candidates.some(expected=>supplied.some(actual=>safeEqual(actual,expected)));}
async function execute(options:PortfolioDirectorOptions){const{result,hydration,persistence}=await withDurableState(()=>runPortfolioDirector(options));return NextResponse.json({ok:true,runtime:storageRuntime(),hydration,persistence,report:result});}
export async function GET(req:Request){if(!process.env.CRON_SECRET)return NextResponse.json({ok:false,error:"CRON_SECRET is not configured",runtime:storageRuntime()},{status:503});if(!cronAuthorized(req))return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});try{return await execute({bootstrap:true,pollInbox:true,runActions:true});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Portfolio cron failed",runtime:storageRuntime()},{status:500});}}
export async function POST(req:Request){if(!operatorAuthorized(req)&&!cronAuthorized(req))return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});try{let body:PortfolioDirectorOptions={};try{body=await req.json() as PortfolioDirectorOptions;}catch{}return await execute(body);}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Portfolio tick failed",runtime:storageRuntime()},{status:500});}}
