export type Language = "en" | "ru";
export type Channel = "email" | "voice" | "linkedin" | "instagram" | "x" | "calendar" | "system";
export type ExecutionMode = "AUTO" | "APPROVE" | "BLOCKED";
export type ActionKind = "send_email" | "publish_post" | "reply" | "call" | "research" | "analyze" | "book_meeting";
export type LeadStage = "new" | "researched" | "contacted" | "replied" | "qualified" | "meeting" | "won" | "lost" | "do_not_contact";
export type ActionStatus = "queued" | "approved" | "running" | "succeeded" | "failed" | "blocked" | "rejected" | "dead_letter";
export type MissionStatus = "active" | "paused" | "completed" | "failed";
export type ReplyIntent = "positive" | "question" | "negative" | "ooo" | "unsubscribe" | "other";
export type RecommendedNextAction = "reply" | "meeting" | "call" | "wait" | "stop" | "review";
export type ContentFormat = "post" | "thread" | "carousel" | "reel_script" | "story";
export type MetricSource = "manual" | "provider" | "system";
export type VoiceCallStatus = "initiated" | "ringing" | "answered" | "completed" | "summarized" | "failed";
export type MeetingStatus = "proposed" | "availability_checked" | "approved" | "booked" | "failed" | "cancelled";

export interface BrandVoice { tone:string[]; writingRules:string[]; avoid:string[]; founderVoice?:string; visualDirection:string[]; channelRules:{x:string[];linkedin:string[];instagram:string[];email:string[];voice:string[]}; }
export interface QualityAssessment { score:number; pass:boolean; issues:string[]; blockingIssues:string[]; }
export interface ProductBrief { name:string; oneLiner:string; targetCustomer:string; pains:string[]; proof:string[]; pricingNotes?:string; forbiddenClaims?:string[]; }
export interface ProductRecord extends ProductBrief { id:string; sourceUrl?:string; notes?:string; positioning:string[]; objections:string[]; useCases:string[]; brandVoice?:BrandVoice; language:Language; createdAt:string; updatedAt:string; }
export interface MissionInput { goal:string; market:string; language:Language; autonomy:"auto"|"approve"|"draft"; productId?:string; }
export interface PlannedAction { id:string; channel:Exclude<Channel,"system">; kind:ActionKind; objective:string; rationale:string; mode:ExecutionMode; scheduledOffsetHours:number; payload:Record<string,unknown>; }
export interface DistributionPlan { missionName:string; thesis:string; audience:string[]; contentPillars:string[]; actions:PlannedAction[]; successMetrics:string[]; stopConditions:string[]; }
export interface ExecuteRequest { channel:Exclude<Channel,"system">; kind:ActionKind; mode:ExecutionMode; payload:Record<string,unknown>; policyContext?:{optedOut?:boolean;doNotCall?:boolean;jurisdictionVerified?:boolean;withinAllowedHours?:boolean}; }
export interface MissionRecord { id:string; input:MissionInput; plan:DistributionPlan; status:MissionStatus; createdAt:string; updatedAt:string; }
export interface DistributionActionRecord extends PlannedAction { recordId:string; missionId:string; status:ActionStatus; scheduledAt:string; createdAt:string; updatedAt:string; approvedAt?:string; rejectedAt?:string; executedAt?:string; error?:string; result?:unknown; retryCount:number; }
export interface ContentDraft { id:string; missionId?:string; channel:"x"|"linkedin"|"instagram"|"email"; language:Language; title:string; body:string; callToAction?:string; status:"draft"|"approved"|"scheduled"|"published"|"failed"; createdAt:string; scheduledAt?:string; format?:ContentFormat; pillar?:string; contentGroupId?:string; requiresMedia?:boolean; mediaUrl?:string; qualityScore?:number; qualityIssues?:string[]; }
export interface Lead { id:string; missionId?:string; company:string; contactName?:string; role?:string; email?:string; phone?:string; country?:string; timezone?:string; language:Language; stage:LeadStage; research?:string; website?:string; fitReason?:string; score?:number; sourceUrls?:string[]; linkedinUrl?:string; instagramUrl?:string; optedOut?:boolean; doNotCall?:boolean; lastReplyAt?:string; nextAction?:string; nextActionAt?:string; }
export interface OutreachSequence { id:string; missionId:string; leadId:string; language:Language; emailInitial:{subject:string;body:string}; emailFollowup:{subject:string;body:string}; linkedinDraft:string; callOpening:string; objectionAngles:string[]; createdAt:string; }
export interface InboundReplyDecision { intent:ReplyIntent; summary:string; confidence:number; recommendedAction:RecommendedNextAction; draftReply:string; nextActionDelayHours:number; urgency:"low"|"medium"|"high"; reasoning:string; }
export interface InboundReply { id:string; externalId:string; threadId?:string; messageId?:string; missionId?:string; leadId:string; channel:"email"; from:string; subject:string; text:string; receivedAt:string; decision:InboundReplyDecision; status:"reviewed"|"actioned"|"stopped"; createdAt:string; }
export interface CallSummary { language:Language; outcome:"no_answer"|"not_interested"|"follow_up"|"qualified"|"meeting"|"do_not_contact"; summary:string; needs:string[]; objections:string[]; commitments:string[]; nextAction:string; nextActionAt?:string; decisionMaker?:string; budgetSignal?:string; urgency?:"low"|"medium"|"high"; }
export interface VoiceTranscriptTurn { speaker:"agent"|"prospect"; text:string; at?:string; }
export interface VoiceCallRecord { id:string; callSid:string; streamSid?:string; missionId?:string; leadId?:string; actionId?:string; objective?:string; status:VoiceCallStatus; providerStatus?:string; transcript:VoiceTranscriptTurn[]; summary?:CallSummary; startedAt?:string; answeredAt?:string; completedAt?:string; durationSeconds?:number; createdAt:string; updatedAt:string; error?:string; }
export interface MeetingRecord { id:string; missionId:string; leadId:string; sourceCallSid?:string; title:string; attendeeEmail:string; attendeeName?:string; start:string; end:string; timezone:string; status:MeetingStatus; availabilityVerified:boolean; availabilityCheckedAt?:string; calendarId?:string; calendarEventId?:string; calendarHtmlLink?:string; meetLink?:string; notes?:string; createdAt:string; updatedAt:string; error?:string; }
export interface PerformanceMetrics { impressions?:number; engagements?:number; clicks?:number; replies?:number; positiveReplies?:number; meetings?:number; conversions?:number; spend?:number; }
export interface PerformanceEvent { id:string; missionId:string; contentId?:string; actionId?:string; channel:Channel; source:MetricSource; metrics:PerformanceMetrics; occurredAt:string; createdAt:string; note?:string; }
export interface LearningRanking { key:string; impressions:number; engagements:number; clicks:number; replies:number; positiveReplies:number; meetings:number; conversions:number; score:number; }
export interface LearningReport { id:string; missionId:string; generatedAt:string; summary:string; channelRankings:LearningRanking[]; pillarRankings:LearningRanking[]; recommendations:string[]; evidenceEventIds:string[]; }
export interface DashboardSnapshot { missions:MissionRecord[]; actions:DistributionActionRecord[]; content:ContentDraft[]; leads:Lead[]; products:ProductRecord[]; outreach:OutreachSequence[]; replies:InboundReply[]; calls:VoiceCallRecord[]; meetings:MeetingRecord[]; performance:PerformanceEvent[]; learnings:LearningReport[]; stats:{activeMissions:number;queuedActions:number;approvalsNeeded:number;completedActions:number;researchedLeads:number;products:number;outreachPrepared:number;inboundReplies:number;positiveReplies:number;voiceCalls:number;meetings:number;bookedMeetings:number;performanceEvents:number;learningReports:number}; }
