"use client";

import {useEffect,useMemo,useState} from "react";
import type {DashboardSnapshot,DistributionActionRecord} from "@/lib/types";

type Provider={id:string;name:string;configured:boolean;capability:string};
type Connections={executionEnabled:boolean;providers:Provider[]};

export default function MeetingsPage(){
  const[state,setState]=useState<DashboardSnapshot|null>(null);const[connections,setConnections]=useState<Connections|null>(null);const[leadId,setLeadId]=useState("");const[start,setStart]=useState("");const[timezone,setTimezone]=useState("UTC");const[busy,setBusy]=useState("");const[notice,setNotice]=useState("Meeting proposals are memory-only until persistent storage is connected.");
  async function refresh(){const[a,b]=await Promise.all([fetch("/api/state",{cache:"no-store"}),fetch("/api/connections",{cache:"no-store"})]);const s=await a.json() as DashboardSnapshot;setState(s);setConnections(await b.json() as Connections);if(!leadId&&s.leads[0])setLeadId(s.leads[0].id);}
  useEffect(()=>{void refresh();},[]);
  const calendarReady=Boolean(connections?.providers.find(p=>p.id==="calendar")?.configured);
  const bookingActions=useMemo(()=>new Map((state?.actions||[]).filter(a=>a.kind==="book_meeting"&&typeof a.payload.meetingId==="string").map(a=>[String(a.payload.meetingId),a])),[state]);
  async function propose(){if(!leadId||!start)return;setBusy("proposal");try{const iso=new Date(start).toISOString();const res=await fetch("/api/meetings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leadId,start:iso,timezone})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Proposal failed");setNotice(`Meeting proposal created for ${data.meeting.attendeeEmail}.`);setStart("");await refresh();}catch(error){setNotice(error instanceof Error?error.message:"Proposal failed");}finally{setBusy("");}}
  async function verify(id:string){setBusy(`verify:${id}`);try{const res=await fetch(`/api/meetings/${id}/verify`,{method:"POST"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Availability check failed");setNotice(data.available?"Slot is free. Calendar booking action is ready for approval.":"Requested slot is busy. Choose another time.");await refresh();}catch(error){setNotice(error instanceof Error?error.message:"Availability check failed");}finally{setBusy("");}}
  async function action(action:DistributionActionRecord,command:"approve"|"execute"){setBusy(`${command}:${action.recordId}`);try{const res=await fetch(`/api/actions/${action.recordId}/${command}`,{method:"POST"});const data=await res.json();if(!res.ok)throw new Error(data.error||`${command} failed`);setNotice(command==="approve"?"Calendar booking approved. Execute it when ready.":connections?.executionEnabled?"Calendar event created and invite sent.":"Dry-run executed; no calendar event was created.");await refresh();}catch(error){setNotice(error instanceof Error?error.message:`${command} failed`);}finally{setBusy("");}}
  const card={border:"1px solid #242831",background:"#0f1115",borderRadius:12,padding:18} as const;const input={width:"100%",height:42,marginTop:6,background:"#0b0d10",color:"#eee",border:"1px solid #242831",borderRadius:8,padding:"0 10px"} as const;
  return <main style={{maxWidth:1200,margin:"0 auto",padding:"36px 24px 70px"}}>
    <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"end",marginBottom:22}}><div><span className="eyebrow">MARGARYAN DISTRIBUTION / MEETINGS</span><h1 style={{fontSize:42,margin:"8px 0 0"}}>Meeting Scheduler</h1><p style={{color:"#8f96a3",maxWidth:760,lineHeight:1.55}}>Explicit meeting agreement → proposal → Google Calendar free/busy → human approval → attendee invite + Google Meet.</p></div><div style={{display:"flex",gap:8}}><a className="ghost" href="/calls" style={{textDecoration:"none"}}>Calls</a><a className="ghost" href="/" style={{textDecoration:"none"}}>Command</a></div></header>
    <div style={{...card,marginBottom:14,borderColor:calendarReady?"#2d5138":"#423c26"}}><strong>{calendarReady?"Google Calendar ready":"Google Calendar not connected"}</strong><p style={{color:"#8f96a3",marginBottom:0}}>{notice}</p></div>
    <section style={{...card,marginBottom:14}}><div className="panelHead"><div><span>MANUAL PROPOSAL</span><h3>Create a meeting only from a known CRM lead</h3></div><span className="pill wait">NO DATABASE</span></div><div style={{display:"grid",gridTemplateColumns:"2fr 1.3fr 1fr auto",gap:10,alignItems:"end",marginTop:14}}><label><small>LEAD</small><select style={input} value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Select lead</option>{(state?.leads||[]).map(lead=><option key={lead.id} value={lead.id}>{lead.company}{lead.email?` · ${lead.email}`:" · no email"}</option>)}</select></label><label><small>START · BROWSER LOCAL TIME</small><input style={input} type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label><small>CALENDAR TIMEZONE</small><input style={input} value={timezone} onChange={e=>setTimezone(e.target.value)} placeholder="America/New_York"/></label><button className="ghost" style={{height:42}} disabled={!leadId||!start||busy==="proposal"} onClick={propose}>{busy==="proposal"?"Creating…":"Create proposal"}</button></div></section>
    <section style={card}><div className="panelHead"><div><span>MEETING PIPELINE</span><h3>Proposed and booked conversations</h3></div><b>{state?.meetings.length||0}</b></div><div style={{display:"grid",gap:10,marginTop:14}}>{!state?.meetings.length&&<div className="empty">No meeting proposals yet. Voice calls with an explicit agreed time will appear here automatically.</div>}{(state?.meetings||[]).map(meeting=>{const lead=state?.leads.find(x=>x.id===meeting.leadId);const booking=bookingActions.get(meeting.id);return <article key={meeting.id} style={{border:"1px solid #20242c",borderRadius:10,padding:14,background:"#0a0c0f"}}><div style={{display:"flex",justifyContent:"space-between",gap:14,alignItems:"start"}}><div><strong style={{fontSize:16}}>{meeting.title}</strong><p style={{color:"#8f96a3",margin:"6px 0"}}>{lead?.company||meeting.attendeeName||meeting.attendeeEmail} · {new Date(meeting.start).toLocaleString()} → {new Date(meeting.end).toLocaleTimeString()} · {meeting.timezone}</p><small>{meeting.attendeeEmail}</small>{meeting.error&&<p style={{color:"#d89a9a"}}>{meeting.error}</p>}</div><span className={`pill ${meeting.status==="booked"?"good":meeting.status==="failed"?"bad":"wait"}`}>{meeting.status}</span></div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}>{meeting.status!=="booked"&&!booking&&<button className="ghost" disabled={busy===`verify:${meeting.id}`} onClick={()=>verify(meeting.id)}>{busy===`verify:${meeting.id}`?"Checking…":calendarReady?"Check free/busy →":"Check free/busy"}</button>}{booking?.mode==="APPROVE"&&booking.status==="queued"&&<button className="ghost" disabled={busy===`approve:${booking.recordId}`} onClick={()=>action(booking,"approve")}>Approve booking</button>}{booking?.mode==="AUTO"&&["approved","queued","failed"].includes(booking.status)&&<button className="ghost" disabled={busy===`execute:${booking.recordId}`} onClick={()=>action(booking,"execute")}>{connections?.executionEnabled?"Create event + invite":"Dry-run booking"}</button>}{meeting.calendarHtmlLink&&<a className="ghost" style={{textDecoration:"none"}} href={meeting.calendarHtmlLink} target="_blank">Calendar event ↗</a>}{meeting.meetLink&&<a className="ghost" style={{textDecoration:"none"}} href={meeting.meetLink} target="_blank">Google Meet ↗</a>}</div></article>})}</div></section>
  </main>;
}
