#!/usr/bin/env node
/**
 * Deterministic offline MP4 master; no AI video API, cloud worker or
 * browser MediaRecorder. Requires operator-local Studio, Playwright + FFmpeg.
 * npm run motion:master -- project.json master.mp4 --fps 30
 * Original score is generated by default and synced to film shot cuts.
 * Optional --voice narration.wav --music licensed-music.mp3 --silent
 * Optional --url http://127.0.0.1:3000/motion
 * Install locally: npm install --no-save playwright
 */
import { readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { spawn, spawnSync } from "node:child_process";
import { once } from "node:events";
import { dirname, resolve, extname } from "node:path";
import process from "node:process";

function parse(argv) {
  const positional=[],opts={};
  for(let i=0;i<argv.length;i++){
    if(argv[i].startsWith("--")){
      const key=argv[i].slice(2);
      if(key==="silent"){opts.silent=true;continue;}
      if(!["url","fps","crf","voice","music","chromium","screen","reference"].includes(key))throw Error("Unknown option: "+key);
      const value=argv[++i];if(!value||value.startsWith("--"))throw Error("Missing value for --"+key);
      opts[key]=value;
    }else positional.push(argv[i]);
  }
  if(positional.length!==2)throw Error("Usage: npm run motion:master -- project.json final.mp4 [--url http://127.0.0.1:3000/motion] [--fps 30] [--crf 18] [--voice audio.wav] [--music music.mp3] [--silent] [--reference source.mp4]");
  return {projectPath:resolve(positional[0]),outputPath:resolve(positional[1]),opts};
}
const run=(cmd,args,options={})=>spawnSync(cmd,args,{encoding:"utf8",timeout:80_000,maxBuffer:2_000_000,...options});
async function makeSheet(file,duration){
  const rate=Math.max(.04,8/Math.max(2,duration));
  const name=file.replace(/\.mp4$/i,"")+"-contact-sheet.jpg";
  const r=run("ffmpeg",["-y","-v","error","-i",file,"-vf",
    "fps="+rate.toFixed(5)+",scale=270:-2,tile=4x2:padding=8:margin=8:color=0x101419",
    "-frames:v","1","-q:v","3",name],{timeout:120_000});
  if(r.status!==0)process.stderr.write("Contact sheet warning: "+(r.stderr||"FFmpeg failed").slice(0,500)+"\n");
  return r.status===0?name:null;
}

let browser,ffmpeg;
try {
  const {projectPath,outputPath,opts}=parse(process.argv.slice(2));
  const url=new URL(opts.url||"http://127.0.0.1:3000/motion");
  if(url.protocol!=="http:"||!["127.0.0.1","localhost","[::1]"].includes(url.hostname)||url.pathname!=="/motion"){
    throw Error("--url must be a local Motion Studio URL: http://127.0.0.1:PORT/motion");
  }
  if(extname(outputPath).toLowerCase()!==".mp4")throw Error("Output must end with .mp4");
  const fps=opts.fps?Number(opts.fps):30;
  if(!Number.isInteger(fps)||fps<24||fps>60)throw Error("FPS must be 24–60");
  const crf=opts.crf?Number(opts.crf):18;
  if(!Number.isInteger(crf)||crf<14||crf>28)throw Error("CRF must be 14–28");

  let project=JSON.parse(await readFile(projectPath,"utf8"));
  if(!project||!Array.isArray(project.scenes)||project.scenes.length<1||project.scenes.length>8)throw Error("Invalid project scenes");
  const duration=project.scenes.reduce((s,x)=>s+Math.max(2,Math.min(8,Number(x.seconds)||4)),0);
  if(duration>64)throw Error("Film exceeds 64-second limit");
  const formats={portrait:[1080,1920],square:[1080,1080],landscape:[1920,1080]};
  const dims=formats[project.format];
  if(!dims)throw Error("Invalid project format");
  const frames=Math.max(1,Math.round(duration*fps));
  if(project.scenes.some(scene=>scene.kind==="screen")&&!opts.screen){
    throw Error("Source screenshot scene requires --screen /path/to/approved-real-product-screenshot.png");
  }
  if(opts.screen){
    const ext=extname(opts.screen).toLowerCase();
    if(![".png",".jpg",".jpeg",".webp"].includes(ext))throw Error("Product screen must be PNG, JPG or WebP");
    const source=await stat(resolve(opts.screen));
    if(!source.isFile()||source.size>12_000_000||source.size<100)throw Error("Invalid product screenshot size");
  }

  for(const file of [opts.voice,opts.music].filter(Boolean)){
    const f=await stat(resolve(file));
    if(!f.isFile()||f.size>250_000_000)throw Error("Oversized/invalid audio: "+file);
  }
  if(opts.voice){
    const speech=run("ffprobe",["-v","error","-show_entries","format=duration","-of","default=nw=1:nk=1",resolve(opts.voice)]);
    const speechSeconds=Number(speech.stdout?.trim());
    if(speech.status!==0||!Number.isFinite(speechSeconds))throw Error("Cannot inspect narration duration");
    if(speechSeconds>duration-.3)throw Error(
      "Narration duration "+speechSeconds.toFixed(1)+"s exceeds safe film ending "+(duration-.3).toFixed(1)+"s. Use FIT FILM TO NARRATION or trim recording."
    );
    process.stdout.write("Narration timing validated: "+speechSeconds.toFixed(1)+"s inside "+duration.toFixed(1)+"s film.\n");
  }
  if(run("ffmpeg",["-version"]).status!==0)throw Error("Install FFmpeg with libx264 support first");
  const {chromium}=await import("playwright").catch(()=>{
    throw Error("Playwright required on render workstation: npm install --no-save playwright");
  });
  browser=await chromium.launch({
    headless:true,
    ...(opts.chromium||process.env.CHROMIUM_EXECUTABLE?{executablePath:opts.chromium||process.env.CHROMIUM_EXECUTABLE}:{})
  });
  const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1,reducedMotion:"no-preference"});
  const errors=[];
  page.on("pageerror",e=>errors.push(e.message));
  const response=await page.goto(url.href,{waitUntil:"domcontentloaded",timeout:45_000});
  if(!response?.ok())throw Error("Local studio did not load. Start npm run dev. HTTP "+response?.status());
  await page.waitForFunction(()=>typeof window.__motionFrame==="function",{timeout:30_000});
  // Preload brand font before recording the first exact frame. Glyph fallback
  // remains available offline, but Armenian-specific typography is reviewed.
  const typography=await page.evaluate(async (language)=>{
    if(language!=="hy")return {language,loaded:true};
    try{
      const fonts=await Promise.race([
        document.fonts.load('700 40px "Noto Sans Armenian"',"Հայերեն"),
        new Promise(resolve=>setTimeout(()=>resolve([]),6000))
      ]);
      return {language,loaded:Array.isArray(fonts)&&fonts.length>0};
    }catch{return {language,loaded:false};}
  },project.language||"en");
  if(!typography.loaded){
    process.stderr.write("WARNING: Armenian-specific font did not load. Inspect final Armenian glyphs in contact sheet.\n");
  }
  await page.evaluate(()=>document.fonts.ready);
  if(opts.screen){
    const extension=extname(opts.screen).toLowerCase();
    const mime=extension===".png"?"image/png":extension===".webp"?"image/webp":"image/jpeg";
    const base64=(await readFile(resolve(opts.screen))).toString("base64");
    await page.waitForFunction(()=>typeof window.__motionInstallScreen==="function",{timeout:10000});
    await page.evaluate(async input=>window.__motionInstallScreen(input),
      {brand:project.brand,mime,base64});
    process.stdout.write("Approved source screenshot loaded into local film session; nothing uploaded.\n");
  }


  // Use precisely the same bounded, deterministic repairs as Studio before
  // rendering every frame. It never fabricates source images or changes copy.
  await page.waitForFunction(()=>typeof window.__motionReview==="function",{timeout:10000});
  const automatic=await page.evaluate(input=>window.__motionReview({project:input}),project);
  if(!automatic?.project||!automatic?.report||!automatic?.contactSheetBase64){
    throw Error("Director did not return a validated project and inspection evidence");
  }
  const reviewedPath=outputPath.replace(/\.mp4$/i,"")+".director.motion.json";
  const repairReportPath=outputPath.replace(/\.mp4$/i,"")+".director-audit.json";
  const inspectPath=outputPath.replace(/\.mp4$/i,"")+".director-contact-sheet.png";
  await mkdir(dirname(outputPath),{recursive:true});
  project=automatic.project;
  await Promise.all([
    writeFile(reviewedPath,JSON.stringify(project,null,2)+"\n"),
    writeFile(repairReportPath,JSON.stringify(automatic.report,null,2)+"\n"),
    writeFile(inspectPath,Buffer.from(automatic.contactSheetBase64,"base64"))
  ]);
  if(!automatic.report.measuredFramePass || automatic.report.after?.blockers>0){
    throw Error("Director cannot clear measured defects. Examine "+repairReportPath+" and repair shots before MP4 export.");
  }
  process.stdout.write("Director inspection: "+automatic.report.iterations.length+
    " measured repair passes; "+automatic.report.changes.length+
    " adjustments. Contact sheet saved: "+inspectPath+"\n");

  if(errors.length)throw Error("Studio runtime error: "+errors.slice(0,3).join("; "));

  // A complete film includes its own soundtrack by default, no uploaded music
  // needed. --music overrides it; --silent explicitly opts out of synthesized
  // score (but preserves recorded narration if provided).
  let scorePath=null;
  if(!opts.music&&!opts.silent){
    scorePath=outputPath.replace(/\.mp4$/i,"")+".score.wav";
    const generated=run(process.execPath,["scripts/motion/score-film.mjs",reviewedPath,scorePath],{timeout:120_000});
    if(generated.status!==0)throw Error("Cannot build original film score: "+(generated.stderr||"unknown").slice(-900));
    process.stdout.write("Soundtrack ready: "+scorePath+"\n");
  }
  const audio=[];
  if(opts.voice)audio.push({path:resolve(opts.voice),vol:1});
  if(opts.music||scorePath)audio.push({path:resolve(opts.music||scorePath),vol:opts.voice?.16:.75});

  const args=["-y","-hide_banner","-loglevel","error","-f","image2pipe","-framerate",String(fps),"-vcodec","png","-i","pipe:0"];
  for(const a of audio)args.push("-i",a.path);
  let audioMap=[];
  if(audio.length){
    const parts=[];
    for(let i=0;i<audio.length;i++){
      parts.push("["+(i+1)+":a:0]volume="+audio[i].vol+",apad,atrim=0:"+duration.toFixed(3)+"[aud"+i+"]");
    }
    parts.push(audio.length>1?
      "[aud0][aud1]amix=inputs=2:duration=first:dropout_transition=0[aout]":
      "[aud0]anull[aout]");
    audioMap=["-filter_complex",parts.join(";"),"-map","0:v:0","-map","[aout]","-c:a","aac","-b:a","192k"];
  } else audioMap=["-an"];
  args.push(...audioMap,"-c:v","libx264","-preset","medium","-crf",String(crf),
    "-pix_fmt","yuv420p","-profile:v","high","-r",String(fps),
    "-t",duration.toFixed(3),"-movflags","+faststart",outputPath);

  await mkdir(dirname(outputPath),{recursive:true});
  ffmpeg=spawn("ffmpeg",args,{stdio:["pipe","ignore","pipe"]});
  let log="",encoderFailed=false;
  ffmpeg.stderr.on("data",chunk=>{log+=String(chunk);if(log.length>6000)log=log.slice(-6000);});
  ffmpeg.stdin.on("error",()=>{encoderFailed=true;});
  let last=0;
  for(let i=0;i<frames;i++){
    if(encoderFailed||ffmpeg.exitCode!==null)throw Error("FFmpeg stopped: "+log);
    const png=await page.evaluate(async ({project,time})=>window.__motionFrame({project,time}),
      {project,time:i/fps});
    const bytes=Buffer.from(png,"base64");
    if(bytes.length<900)throw Error("Empty frame "+i);
    if(!ffmpeg.stdin.write(bytes))await once(ffmpeg.stdin,"drain");
    const pct=Math.floor((i+1)*100/frames);
    if(pct>=last+10){last=pct;process.stdout.write("Rendered "+pct+"% ("+(i+1)+"/"+frames+")\n");}
  }
  ffmpeg.stdin.end();
  const [status]=await once(ffmpeg,"close");
  if(status!==0)throw Error("FFmpeg encode failed: "+log.slice(-1700));
  const probe=run("ffprobe",["-v","error","-show_entries","stream=index,codec_name,codec_type,width,height,avg_frame_rate","-show_entries","format=duration","-of","json",outputPath]);
  if(probe.status!==0)throw Error("Encoded MP4 could not be probed");
  const parsed=JSON.parse(probe.stdout);
  const video=parsed.streams?.find(x=>x.codec_type==="video");
  const track=parsed.streams?.find(x=>x.codec_type==="audio");
  if(!video||video.width!==dims[0]||video.height!==dims[1]||video.codec_name!=="h264"){
    throw Error("Encoded master format/dimensions incorrect");
  }
  if(audio.length&&!track)throw Error("Audio requested but MP4 audio track missing");
  // Deliver platform-native sidecars as part of the video master bundle.
  const captionsURL=new URL("/api/motion/captions",url.href);
  const captionsResponse=await fetch(captionsURL,{
    method:"POST",headers:{"content-type":"application/json"},
    body:JSON.stringify({project}),signal:AbortSignal.timeout(15_000)
  });
  if(!captionsResponse.ok)throw Error("Media encoded but caption sidecars failed: HTTP "+captionsResponse.status);
  const captions=await captionsResponse.json();
  if(!captions.srt||!captions.vtt||!captions.voiceScript)throw Error("Caption endpoint did not return a complete bundle");
  const prefix=outputPath.replace(/\.mp4$/i,"");
  await Promise.all([
    writeFile(prefix+".srt",captions.srt),
    writeFile(prefix+".vtt",captions.vtt),
    writeFile(prefix+"-narration-guide.txt",captions.voiceScript)
  ]);
  let referenceComparison=null;
  if(opts.reference){
    const inspect=run(process.execPath,["scripts/motion/compare-reference.mjs",outputPath,resolve(opts.reference)],{
      timeout:210_000,maxBuffer:2_000_000
    });
    if(inspect.status!==0)throw Error("Reference comparison failed after video export: "+String(inspect.stderr||"unknown").slice(-900));
    const parsed=JSON.parse(inspect.stdout);
    referenceComparison={
      report:parsed.report,
      contactSheet:parsed.contactSheet,
      signal:parsed.signal,
      humanReviewRequired:true
    };
  }
  const sheet=await makeSheet(outputPath,duration);
  const report={
    engine:"MARGARYAN MOTION OS / OFFLINE MASTER",frames,expectedFps:fps,
    expectedDuration:duration,file:outputPath,codec:video.codec_name,
    width:video.width,height:video.height,audioCodec:track?.codec_name||null,
    audioIncluded:!!track,voiceRequested:!!opts.voice,musicRequested:!!opts.music,
    originalScoreGenerated:!!scorePath,originalScoreFile:scorePath,
    contactSheet:sheet,captionFiles:[".srt",".vtt","-narration-guide.txt"],
    referenceComparison,
    voiceTimingVerified:Boolean(opts.voice),
    directorAudit:repairReportPath,directorContactSheet:inspectPath,
    directorRepairs:automatic.report.changes.length,unresolvedDirectorReviews:automatic.report.remaining,
    note:"Technical checks cannot independently certify aesthetics, truth of claims, or music/voice licensing."
  };
  await writeFile(outputPath.replace(/\.mp4$/i,"")+".render-report.json",JSON.stringify(report,null,2)+"\n");
  process.stdout.write("Motion Master complete:\n"+JSON.stringify(report,null,2)+"\n");
}catch(error){
  process.stderr.write("Motion Master: "+(error instanceof Error?error.message:String(error))+"\n");
  process.exitCode=1;
}finally{
  if(ffmpeg&&!ffmpeg.killed&&ffmpeg.exitCode===null)ffmpeg.kill("SIGTERM");
  if(browser)await browser.close().catch(()=>undefined);
}
