import { NextResponse } from "next/server";
import { distributionStore } from "@/lib/store";
import type { Channel, MetricSource, PerformanceMetrics } from "@/lib/types";

const channels=new Set<Channel>(["email","voice","linkedin","instagram","x","system"]);const sources=new Set<MetricSource>(["manual","provider","system"]);const metricKeys:Array<keyof PerformanceMetrics>=["impressions","engagements","clicks","replies","positiveReplies","meetings","conversions","spend"];
function cleanMetrics(input:unknown){const raw=(input&&typeof input==="object"?input:{}) as Record<string,unknown>;const metrics:PerformanceMetrics={};for(const key of metricKeys){if(raw[key]===undefined)continue;const value=Number(raw[key]);if(!Number.isFinite(value)||value<0)throw new Error(`${key} must be a non-negative number`);metrics[key]=value;}if(!Object.keys(metrics).length)throw new Error("At least one metric is required");return metrics;}

export async function GET(req:Request){const url=new URL(req.url);const missionId=url.searchParams.get("missionId");const events=distributionStore.listPerformance().filter(event=>!missionId||event.missionId===missionId);return NextResponse.json({events});}
export async function POST(req:Request){
 try{const body=await req.json() as Record<string,unknown>;const missionId=String(body.missionId||"");if(!missionId||!distributionStore.getMission(missionId))return NextResponse.json({error:"Valid missionId is required"},{status:400});const channel=String(body.channel||"") as Channel;if(!channels.has(channel))return NextResponse.json({error:"Invalid channel"},{status:400});const source=(body.source?String(body.source):"manual") as MetricSource;if(!sources.has(source))return NextResponse.json({error:"Invalid source"},{status:400});const contentId=body.contentId?String(body.contentId):undefined;if(contentId){const content=distributionStore.getContent(contentId);if(!content||content.missionId!==missionId)return NextResponse.json({error:"contentId does not belong to mission"},{status:400});}const actionId=body.actionId?String(body.actionId):undefined;if(actionId){const action=distributionStore.getAction(actionId);if(!action||action.missionId!==missionId)return NextResponse.json({error:"actionId does not belong to mission"},{status:400});}const occurredAt=body.occurredAt?new Date(String(body.occurredAt)):new Date();if(Number.isNaN(occurredAt.getTime()))return NextResponse.json({error:"Invalid occurredAt"},{status:400});const event=distributionStore.addPerformance({missionId,contentId,actionId,channel,source,metrics:cleanMetrics(body.metrics),occurredAt:occurredAt.toISOString(),note:body.note?String(body.note).slice(0,500):undefined});return NextResponse.json({event});}
 catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Metric ingestion failed"},{status:400});}
}
