"use client";

import { useEffect, useState } from "react";
import type { DashboardSnapshot } from "@/lib/types";

export default function AutopilotPage(){
  const [state,setState]=useState<DashboardSnapshot|null>(null);const [missionId,setMissionId]=useState("");const [leadTarget,setLeadTarget]=useState(8);const [researchPerTick,setResearchPerTick]=useState(5);const [outreachPerTick,setOutreachPerTick]=useState(3);const [smmDays,setSmmDays]=useState(7);const [secret,setSecret]=useState("");const [busy,setBusy]=useState(false);const [report,setReport]=useState("Autopilot has not run in this browser session.");
  async function refresh(){const res=await fetch("/api/state",{cache:"no-store"});const data=await res.json() as DashboardSnapshot;setState(data);if(!missionId&&data.missions[0])setMissionId(data.missions[0].id);}
  useEffect(()=>{void refresh();},[]);
  async function run(){setBusy(true);setReport("Autopilot is evaluating mission state…");try{const headers:Record<string,string>={"Content-Type":"application/json"};if(secret)headers["x-autopilot-secret"]=secret;const res=await fetch("/api/autopilot/tick",{method:"POST",headers,body:JSON.stringify({missionId:missionId||undefined,leadTarget,researchPerTick,outreachPerTick,smmDays,pollInbox:true,runActions:true})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Autopilot failed");setReport(JSON.stringify(data.report,null,2));await refresh();}catch(error){setReport(error instanceof Error?error.message:"Autopilot failed");}finally{setBusy(false);}}
  const card={border:"1px solid #242831",background:"#0f1115",borderRadius:12,padding:18} as const;
  const inputStyle={width:"100%",height:42,marginTop:6,background:"#0b0d10",color:"#eee",border:"1px solid #242831",borderRadius:8,padding:"0 10px"} as const;
  return <main style={{maxWidth:1180,margin:"0 auto",padding:"36px 24px 70px"}}>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,marginBottom:24}}><div><span className="eyebrow">MARGARYAN DISTRIBUTION / AUTOPILOT</span><h1 style={{fontSize:42,margin:"8px 0 0"}}>Distribution Director</h1><p style={{color:"#8f96a3",maxWidth:720,lineHeight:1.55}}>One tick evaluates the mission, fills missing pipeline work, prepares governed outreach and SMM, checks known-lead replies, then executes only actions already allowed by policy.</p></div><a href="/" className="ghost" style={{textDecoration:"none"}}>← Command</a></header>
    <section style={{...card,marginBottom:14}}><div className="panelHead"><div><span>CONTROL SURFACE</span><h3>Autopilot limits</h3></div><span className="pill wait">NO DATABASE</span></div><div style={{display:"grid",gridTemplateColumns:"2fr repeat(4,1fr)",gap:10,marginTop:16}}><label><small>MISSION</small><select value={missionId} onChange={e=>setMissionId(e.target.value)} style={inputStyle}><option value="">All active missions</option>{(state?.missions||[]).map(item=><option key={item.id} value={item.id}>{item.plan.missionName}</option>)}</select></label><label><small>LEAD TARGET</small><input type="number" min={1} max={50} value={leadTarget} onChange={e=>setLeadTarget(Number(e.target.value))} style={inputStyle}/></label><label><small>RESEARCH / TICK</small><input type="number" min={1} max={10} value={researchPerTick} onChange={e=>setResearchPerTick(Number(e.target.value))} style={inputStyle}/></label><label><small>OUTREACH / TICK</small><input type="number" min={1} max={10} value={outreachPerTick} onChange={e=>setOutreachPerTick(Number(e.target.value))} style={inputStyle}/></label><label><small>SMM DAYS</small><input type="number" min={3} max={14} value={smmDays} onChange={e=>setSmmDays(Number(e.target.value))} style={inputStyle}/></label></div><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:10,alignItems:"end",marginTop:12}}><label><small>AUTOPILOT SECRET · OPTIONAL UNTIL CONFIGURED</small><input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Never stored by this page" style={inputStyle}/></label><button className="ghost" onClick={run} disabled={busy||!state?.missions.length} style={{height:42}}>{busy?"Running director…":"Run Autopilot →"}</button></div></section>
    <section style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginBottom:14}}>{[["MISSIONS",state?.stats.activeMissions||0],["LEADS",state?.stats.researchedLeads||0],["OUTREACH",state?.stats.outreachPrepared||0],["APPROVALS",state?.stats.approvalsNeeded||0]].map(([label,value])=><article key={String(label)} style={card}><span className="eyebrow">{label}</span><strong style={{display:"block",fontSize:30,marginTop:9}}>{value}</strong></article>)}</section>
    <section style={card}><div className="panelHead"><div><span>DIRECTOR TRACE</span><h3>What the agent decided and did</h3></div></div><pre style={{whiteSpace:"pre-wrap",overflow:"auto",minHeight:300,maxHeight:720,background:"#08090b",border:"1px solid #1b1e25",borderRadius:9,padding:15,color:"#aeb5bf",fontSize:11,lineHeight:1.6,marginTop:14}}>{report}</pre></section>
  </main>;
}
