"use client";

import {useEffect,useMemo,useState} from "react";
import type {DashboardSnapshot,DistributionActionRecord} from "@/lib/types";

type StateResponse=DashboardSnapshot&{runtime?:{execution?:string}};
function when(value?:string){if(!value)return"—";return new Intl.DateTimeFormat("en",{month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}

export default function CallsPage(){
  const[state,setState]=useState<StateResponse|null>(null);const[busy,setBusy]=useState("");const[notice,setNotice]=useState("Voice workspace is ready. Live calls remain policy-gated.");
  const[jurisdiction,setJurisdiction]=useState(false);const[hours,setHours]=useState(false);const[disclosure,setDisclosure]=useState(false);
  async function refresh(){const res=await fetch("/api/state",{cache:"no-store"});setState(await res.json() as StateResponse);}
  useEffect(()=>{void refresh();},[]);
  const voiceActions=useMemo(()=>(state?.actions||[]).filter(action=>action.channel==="voice"&&action.kind==="call"&&["blocked","queued","approved","failed"].includes(action.status)),[state]);
  async function clear(action:DistributionActionRecord){setBusy(`clear:${action.recordId}`);try{const res=await fetch(`/api/actions/${action.recordId}/voice-clearance`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jurisdictionVerified:jurisdiction,withinAllowedHours:hours,aiDisclosureAcknowledged:disclosure})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Voice clearance failed");setNotice(`Cleared ${action.objective}. It is approved but has not been called yet.`);await refresh();}catch(error){setNotice(error instanceof Error?error.message:"Voice clearance failed");}finally{setBusy("");}}
  async function execute(action:DistributionActionRecord){setBusy(`call:${action.recordId}`);try{const res=await fetch(`/api/actions/${action.recordId}/execute`,{method:"POST"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Call failed");setNotice(`Call action executed in ${state?.runtime?.execution||"current"} mode.`);await refresh();}catch(error){setNotice(error instanceof Error?error.message:"Call failed");}finally{setBusy("");}}
  const card={border:"1px solid #242831",background:"#0f1115",borderRadius:12,padding:18} as const;
  return <main style={{maxWidth:1240,margin:"0 auto",padding:"36px 24px 70px"}}>
    <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"end",marginBottom:24}}><div><span className="eyebrow">MARGARYAN DISTRIBUTION / VOICE</span><h1 style={{fontSize:42,margin:"8px 0 0"}}>AI Sales Calls</h1><p style={{maxWidth:760,color:"#8f96a3",lineHeight:1.55}}>Policy-gated outbound calls with realtime conversation, transcript capture, factual CRM summary and next-best-action handoff.</p></div><div style={{display:"flex",gap:8}}><a href="/autopilot" className="ghost" style={{textDecoration:"none"}}>Autopilot</a><a href="/" className="ghost" style={{textDecoration:"none"}}>Command</a></div></header>
    <div className="notice" style={{marginBottom:14}}><span/> {notice}</div>
    <section style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginBottom:14}}>{[["CALLS",state?.stats.voiceCalls||0],["MEETINGS",state?.stats.meetings||0],["PENDING VOICE",voiceActions.length],["RUNTIME",state?.runtime?.execution||"dry-run"]].map(([label,value])=><article key={String(label)} style={card}><span className="eyebrow">{label}</span><strong style={{display:"block",fontSize:28,marginTop:9}}>{value}</strong></article>)}</section>
    <section style={{...card,marginBottom:14}}><div className="panelHead"><div><span>VOICE CLEARANCE</span><h3>Explicit operator verification</h3></div><span className="pill wait">REQUIRED FOR LIVE CALLS</span></div><p style={{color:"#8f96a3",lineHeight:1.55}}>These checks do not infer legality automatically. Confirm them only after verifying the target jurisdiction and the recipient&apos;s local calling window.</p><div style={{display:"flex",gap:18,flexWrap:"wrap",marginTop:14}}><label><input type="checkbox" checked={jurisdiction} onChange={e=>setJurisdiction(e.target.checked)}/> Jurisdiction verified</label><label><input type="checkbox" checked={hours} onChange={e=>setHours(e.target.checked)}/> Calling hours verified</label><label><input type="checkbox" checked={disclosure} onChange={e=>setDisclosure(e.target.checked)}/> AI disclosure acknowledged</label></div></section>
    <section style={{...card,marginBottom:14}}><div className="panelHead"><div><span>CALL QUEUE</span><h3>Blocked, approved and retryable voice actions</h3></div><b>{voiceActions.length}</b></div><div style={{display:"grid",gap:10,marginTop:14}}>{voiceActions.length===0&&<div className="empty">No pending voice actions. Autopilot/outreach will create them when a lead has a public business phone.</div>}{voiceActions.map(action=><article key={action.recordId} style={{border:"1px solid #20242c",borderRadius:10,padding:14,display:"grid",gridTemplateColumns:"1fr auto",gap:14,alignItems:"center"}}><div><strong>{action.objective}</strong><p style={{margin:"6px 0",color:"#8f96a3",fontSize:13}}>{action.rationale}</p><small>{action.status.toUpperCase()} · scheduled {when(action.scheduledAt)}</small></div><div style={{display:"flex",gap:8}}>{action.status==="blocked"&&<button className="ghost" disabled={busy!==""||!jurisdiction||!hours||!disclosure} onClick={()=>void clear(action)}>{busy===`clear:${action.recordId}`?"Clearing…":"Clear voice"}</button>}{["approved","queued","failed"].includes(action.status)&&<button className="ghost" disabled={busy!==""} onClick={()=>void execute(action)}>{busy===`call:${action.recordId}`?"Calling…":"Execute call"}</button>}</div></article>)}</div></section>
    <section style={card}><div className="panelHead"><div><span>CALL MEMORY</span><h3>Transcripts and CRM outcomes</h3></div><b>{state?.calls.length||0}</b></div><div style={{display:"grid",gap:12,marginTop:14}}>{(state?.calls||[]).length===0&&<div className="empty">No voice calls have been recorded in this process yet.</div>}{(state?.calls||[]).map(call=><article key={call.id} style={{border:"1px solid #20242c",borderRadius:10,padding:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><span className="eyebrow">{call.providerStatus||call.status}</span><h3 style={{margin:"5px 0"}}>{call.summary?.outcome||"Awaiting summary"}</h3><small>{call.callSid} · {when(call.startedAt)} → {when(call.completedAt)}</small></div><div style={{maxWidth:520,textAlign:"right"}}><strong>{call.summary?.summary||call.objective||"Conversation in progress"}</strong>{call.summary?.nextAction&&<p style={{color:"#aeb5bf",margin:"8px 0 0"}}>Next: {call.summary.nextAction}{call.summary.nextActionAt?` · ${when(call.summary.nextActionAt)}`:""}</p>}</div></div>{call.summary&&<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,marginTop:14}}><div><small>NEEDS</small><p>{call.summary.needs.join(" · ")||"—"}</p></div><div><small>OBJECTIONS</small><p>{call.summary.objections.join(" · ")||"—"}</p></div><div><small>COMMITMENTS</small><p>{call.summary.commitments.join(" · ")||"—"}</p></div></div>}<details style={{marginTop:12}}><summary style={{cursor:"pointer"}}>Transcript · {call.transcript.length} turns</summary><div style={{marginTop:10,background:"#08090b",borderRadius:9,padding:12}}>{call.transcript.length===0?<span style={{color:"#777"}}>No transcript captured.</span>:call.transcript.map((turn,index)=><p key={`${call.id}-${index}`} style={{margin:"6px 0",lineHeight:1.5}}><b style={{fontSize:11}}>{turn.speaker.toUpperCase()}</b> · {turn.text}</p>)}</div></details></article>)}</div></section>
  </main>;
}
