"use client";

import {useParams} from "next/navigation";
import {useEffect,useState} from "react";
import type {Lead,MissionRecord,ProductRecord} from "@/lib/types";

type TimelineEvent={id:string;at:string;type:string;channel:string;title:string;summary:string;status?:string;meta?:Record<string,unknown>};
type Lead360={lead:Lead;mission?:MissionRecord;product?:ProductRecord;brief:{headline:string;relationship:string;nextAction:string;nextActionAt?:string;nextMeeting?:{id:string;start:string;status:string;meetLink?:string};knownNeeds:string[];knownObjections:string[];commitments:string[]};events:TimelineEvent[]};
function when(value?:string){if(!value)return"—";return new Intl.DateTimeFormat("en",{year:"numeric",month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}

export default function LeadDetailPage(){
 const params=useParams<{id:string}>();const[data,setData]=useState<Lead360|null>(null);const[error,setError]=useState("");async function refresh(){setError("");const res=await fetch(`/api/leads/${encodeURIComponent(params.id)}/timeline`,{cache:"no-store"});const body=await res.json();if(!res.ok){setError(body.error||"Lead not found");return;}setData(body as Lead360);}useEffect(()=>{void refresh();},[params.id]);
 const card={border:"1px solid #242831",background:"#0f1115",borderRadius:12,padding:18} as const;
 if(error)return <main style={{maxWidth:900,margin:"0 auto",padding:40}}><div style={card}>{error} · <a href="/leads">Back to leads</a></div></main>;
 if(!data)return <main style={{maxWidth:900,margin:"0 auto",padding:40}}>Loading lead 360…</main>;
 const{lead,brief,events}=data;
 return <main style={{maxWidth:1200,margin:"0 auto",padding:"36px 24px 70px"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,marginBottom:22}}><div><span className="eyebrow">LEAD 360 / {lead.stage.toUpperCase()}</span><h1 style={{fontSize:42,margin:"8px 0 0"}}>{lead.company}</h1><p style={{color:"#8f96a3",maxWidth:760,lineHeight:1.55}}>{lead.fitReason||lead.research||"Unified relationship record."}</p></div><div style={{display:"flex",gap:8}}><a className="ghost" href="/meetings" style={{textDecoration:"none"}}>Meetings</a><a className="ghost" href="/leads" style={{textDecoration:"none"}}>← Leads</a></div></header>
 <section style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:14,marginBottom:14}}><article style={card}><span className="eyebrow">RELATIONSHIP BRIEF</span><h2 style={{margin:"8px 0 10px",fontSize:25}}>{brief.headline}</h2><p style={{color:"#b5bbc5",lineHeight:1.6}}>{brief.relationship}</p><div style={{marginTop:16,borderTop:"1px solid #20242c",paddingTop:14}}><small>NEXT BEST ACTION</small><strong style={{display:"block",fontSize:18,marginTop:5}}>{brief.nextAction}</strong>{brief.nextActionAt&&<p style={{color:"#8f96a3",margin:"6px 0 0"}}>{when(brief.nextActionAt)}</p>}</div></article><article style={card}><span className="eyebrow">CRM PROFILE</span><dl style={{display:"grid",gap:10,marginTop:12}}><div><dt>Stage</dt><dd>{lead.stage}</dd></div><div><dt>Score</dt><dd>{lead.score??"—"}</dd></div><div><dt>Email</dt><dd>{lead.email||"—"}</dd></div><div><dt>Phone</dt><dd>{lead.phone||"—"}</dd></div><div><dt>Market</dt><dd>{lead.country||data.mission?.input.market||"—"}</dd></div><div><dt>Product</dt><dd>{data.product?.name||"—"}</dd></div></dl></article></section>
 <section style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,marginBottom:14}}>{[["KNOWN NEEDS",brief.knownNeeds],["OBJECTIONS",brief.knownObjections],["COMMITMENTS",brief.commitments]].map(([label,items])=><article key={String(label)} style={card}><span className="eyebrow">{String(label)}</span><div style={{marginTop:10,color:"#b0b6c0",lineHeight:1.5}}>{(items as string[]).length?(items as string[]).map((item,index)=><p key={index} style={{margin:"6px 0"}}>• {item}</p>):<span>None captured yet.</span>}</div></article>)}</section>
 {brief.nextMeeting&&<section style={{...card,marginBottom:14,borderColor:"#2d5138"}}><div className="panelHead"><div><span>NEXT MEETING</span><h3>{when(brief.nextMeeting.start)}</h3></div><span className="pill good">{brief.nextMeeting.status}</span></div>{brief.nextMeeting.meetLink&&<a className="ghost" style={{display:"inline-block",textDecoration:"none",marginTop:12}} href={brief.nextMeeting.meetLink} target="_blank">Open Google Meet ↗</a>}</section>}
 <section style={card}><div className="panelHead"><div><span>RELATIONSHIP TIMELINE</span><h3>Every known interaction</h3></div><b>{events.length}</b></div><div style={{display:"grid",gap:9,marginTop:14}}>{events.length===0&&<div className="empty">No relationship events yet.</div>}{events.map(event=><article key={event.id} style={{display:"grid",gridTemplateColumns:"150px 110px 1fr auto",gap:12,border:"1px solid #20242c",borderRadius:9,padding:12,alignItems:"start",background:"#0a0c0f"}}><small>{when(event.at)}</small><div><span className="eyebrow">{event.channel}</span><p style={{fontSize:11,margin:"4px 0",color:"#8f96a3"}}>{event.type}</p></div><div><strong>{event.title}</strong><p style={{color:"#9ba2ad",fontSize:12,lineHeight:1.5,margin:"5px 0 0"}}>{event.summary}</p></div>{event.status&&<span className={`pill ${["succeeded","summarized","booked","qualified","meeting"].includes(event.status)?"good":["failed","blocked","dead_letter","lost"].includes(event.status)?"bad":"wait"}`}>{event.status}</span>}</article>)}</div></section></main>;
}
