"use client";

import {useEffect,useState} from "react";
import type {ProductRecord} from "@/lib/types";

export default function ProductsPage(){
 const[products,setProducts]=useState<ProductRecord[]>([]);const[selected,setSelected]=useState("");async function refresh(){const res=await fetch("/api/products",{cache:"no-store"});const data=await res.json() as{products:ProductRecord[]};setProducts(data.products||[]);if(!selected&&data.products?.[0])setSelected(data.products[0].id);}useEffect(()=>{void refresh();},[]);const product=products.find(x=>x.id===selected)||products[0];const card={border:"1px solid #242831",background:"#0f1115",borderRadius:12,padding:18} as const;
 return <main style={{maxWidth:1200,margin:"0 auto",padding:"36px 24px 80px"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,marginBottom:22}}><div><span className="eyebrow">MARGARYAN DISTRIBUTION / INTELLIGENCE</span><h1 style={{fontSize:42,margin:"8px 0 0"}}>Product + Brand Brain</h1><p style={{color:"#8f96a3",maxWidth:760,lineHeight:1.55}}>Verified product truth controls what the agent may claim. Brand Brain controls how the agent sounds across channels.</p></div><a className="ghost" href="/#products" style={{textDecoration:"none"}}>Build product brain →</a></header>
 <section style={{display:"grid",gridTemplateColumns:"280px 1fr",gap:14}}><aside style={card}><span className="eyebrow">PRODUCTS</span><div style={{display:"grid",gap:7,marginTop:12}}>{products.length===0&&<div className="empty">No product brains in this process.</div>}{products.map(item=><button key={item.id} onClick={()=>setSelected(item.id)} style={{textAlign:"left",padding:12,borderRadius:9,border:item.id===product?.id?"1px solid #4b5669":"1px solid #20242c",background:item.id===product?.id?"#141820":"#0a0c0f",color:"#eee"}}><strong>{item.name}</strong><small style={{display:"block",color:"#8f96a3",marginTop:5}}>{item.language.toUpperCase()} · {item.proof.length} proof item(s)</small></button>)}</div></aside>
 <div style={{display:"grid",gap:14}}>{!product?<section style={card}><div className="empty">Build a Product Brain from Command Center first.</div></section>:<><section style={card}><span className="eyebrow">PRODUCT TRUTH</span><h2 style={{fontSize:27,margin:"8px 0"}}>{product.name}</h2><p style={{color:"#b3bac4",lineHeight:1.6}}>{product.oneLiner}</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14,marginTop:16}}><div><small>ICP</small><p>{product.targetCustomer||"Not verified"}</p><small>PAINS</small>{product.pains.length?product.pains.map((x,i)=><p key={i}>• {x}</p>):<p>—</p>}<small>USE CASES</small>{product.useCases.length?product.useCases.map((x,i)=><p key={i}>• {x}</p>):<p>—</p>}</div><div><small>VERIFIED PROOF</small>{product.proof.length?product.proof.map((x,i)=><p key={i}>✓ {x}</p>):<p>No verified proof stored.</p>}<small>FORBIDDEN CLAIMS</small>{product.forbiddenClaims?.map((x,i)=><p key={i}>× {x}</p>)}<small>OBJECTIONS</small>{product.objections.map((x,i)=><p key={i}>• {x}</p>)}</div></div></section>
 <section style={card}><div className="panelHead"><div><span>BRAND BRAIN</span><h3>How the agent should sound</h3></div><span className={`pill ${product.brandVoice?"good":"wait"}`}>{product.brandVoice?"ACTIVE":"DEFAULT"}</span></div>{product.brandVoice?<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14,marginTop:14}}><div><small>TONE</small><p>{product.brandVoice.tone.join(" · ")}</p><small>WRITING RULES</small>{product.brandVoice.writingRules.map((x,i)=><p key={i}>• {x}</p>)}<small>AVOID</small>{product.brandVoice.avoid.map((x,i)=><p key={i}>× {x}</p>)}{product.brandVoice.founderVoice&&<><small>FOUNDER VOICE</small><p>{product.brandVoice.founderVoice}</p></>}</div><div><small>VISUAL DIRECTION</small><p>{product.brandVoice.visualDirection.join(" · ")}</p>{Object.entries(product.brandVoice.channelRules).map(([channel,rules])=><div key={channel} style={{marginTop:10}}><small>{channel.toUpperCase()}</small><p>{rules.join(" · ")}</p></div>)}</div></div>:<div className="empty" style={{marginTop:14}}>This older Product Brain has no Brand Brain yet. Rebuild it from the Command Center to generate one.</div>}</section></>}</div></section></main>;
}
