"use client";

import {useEffect,useState} from "react";
import type {ExecutiveBrief} from "@/lib/agent/executive-brief";

function when(value?:string){if(!value)return"—";return new Intl.DateTimeFormat("en",{month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}

export default function BriefPage(){
 const[data,setData]=useState<ExecutiveBrief|null>(null);const[hours,setHours]=useState(24);const[busy,setBusy]=useState(false);async function refresh(nextHours=hours){setBusy(true);try{const res=await fetch(`/api/brief?hours=${nextHours}`,{cache:"no-store"});setData(await res.json() as ExecutiveBrief);}finally{setBusy(false);}}useEffect(()=>{void refresh(24);},[]);
 const card={border:"1px solid #242831",background:"#0f1115",borderRadius:12,padding:18} as const;
 const metrics=data?.metrics;
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"36px 24px 80px"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,marginBottom:22}}><div><span className="eyebrow">MARGARYAN DISTRIBUTION / EXECUTIVE</span><h1 style={{fontSize:42,margin:"8px 0 0"}}>Distribution Brief</h1><p style={{color:"#8f96a3",maxWidth:760,lineHeight:1.55}}>{data?.headline||"Building factual distribution brief…"}</p></div><div style={{display:"flex",gap:8,alignItems:"center"}}><select value={hours} onChange={e=>{const value=Number(e.target.value);setHours(value);void refresh(value);}} style={{height:39,background:"#0b0d10",color:"#eee",border:"1px solid #242831",borderRadius:8,padding:"0 10px"}}><option value={24}>24 hours</option><option value={48}>48 hours</option><option value={168}>7 days</option></select><button className="ghost" disabled={busy} onClick={()=>void refresh()}>{busy?"Refreshing…":"Refresh"}</button></div></header>
 <section style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:10,marginBottom:14}}>{[["POSITIVE REPLIES",metrics?.positiveReplies||0],["VOICE CALLS",metrics?.voiceCalls||0],["MEETINGS AGREED",metrics?.meetingsAgreed||0],["BOOKED",metrics?.meetingsBooked||0],["APPROVALS",metrics?.approvalsNeeded||0]].map(([label,value])=><article key={String(label)} style={card}><span className="eyebrow">{label}</span><strong style={{display:"block",fontSize:28,marginTop:9}}>{value}</strong></article>)}</section>
 <section style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14,marginBottom:14}}><article style={card}><div className="panelHead"><div><span>WINS</span><h3>What moved forward</h3></div></div><div style={{marginTop:12}}>{data?.wins.length?data.wins.map((item,index)=><p key={index} style={{lineHeight:1.55}}>✓ {item}</p>):<div className="empty">No explicit wins recorded in this window.</div>}</div></article><article style={card}><div className="panelHead"><div><span>NEEDS YOU</span><h3>Human attention</h3></div></div><div style={{marginTop:12}}>{data?.attention.length?data.attention.map((item,index)=><p key={index} style={{lineHeight:1.55}}>• {item}</p>):<div className="empty">No approvals or operational exceptions require attention.</div>}</div></article></section>
 <section style={{...card,marginBottom:14}}><div className="panelHead"><div><span>CONVERSATIONS</span><h3>What prospects said</h3></div><b>{data?.conversations.length||0}</b></div><div style={{display:"grid",gap:9,marginTop:12}}>{!data?.conversations.length&&<div className="empty">No inbound replies or summarized calls in this window.</div>}{data?.conversations.map((item,index)=><article key={`${item.company}-${index}`} style={{border:"1px solid #20242c",borderRadius:9,padding:13,display:"grid",gridTemplateColumns:"1.1fr 100px 2fr",gap:12}}><div><strong>{item.company}</strong>{item.nextActionAt&&<p style={{fontSize:11,color:"#8f96a3",margin:"5px 0"}}>Next {when(item.nextActionAt)}</p>}</div><div><span className="eyebrow">{item.channel}</span><p style={{fontSize:11,margin:"5px 0"}}>{item.outcome}</p></div><div><p style={{margin:0,color:"#b2b8c2",lineHeight:1.5}}>{item.summary}</p>{item.nextAction&&<small>Next: {item.nextAction}</small>}</div></article>)}</div></section>
 <section style={card}><div className="panelHead"><div><span>NEXT MOVES</span><h3>Highest-priority actions</h3></div></div><ol style={{paddingLeft:22,lineHeight:1.8}}>{data?.nextMoves.map((item,index)=><li key={index}>{item}</li>)}</ol><small style={{color:"#777"}}>Generated {when(data?.generatedAt)} · current storage is process memory.</small></section></main>;
}
