"use client";

import {useEffect,useMemo,useState} from "react";
import type {Lead} from "@/lib/types";

export default function LeadsPage(){
 const[leads,setLeads]=useState<Lead[]>([]);const[query,setQuery]=useState("");const[stage,setStage]=useState("all");async function refresh(){const res=await fetch("/api/leads",{cache:"no-store"});const data=await res.json() as{leads:Lead[]};setLeads(data.leads||[]);}useEffect(()=>{void refresh();},[]);
 const filtered=useMemo(()=>leads.filter(lead=>(stage==="all"||lead.stage===stage)&&(!query||`${lead.company} ${lead.contactName||""} ${lead.email||""}`.toLowerCase().includes(query.toLowerCase()))),[leads,query,stage]);
 const card={border:"1px solid #242831",background:"#0f1115",borderRadius:12,padding:18} as const;const control={height:40,background:"#0b0d10",color:"#eee",border:"1px solid #242831",borderRadius:8,padding:"0 10px"} as const;
 return <main style={{maxWidth:1200,margin:"0 auto",padding:"36px 24px 70px"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,marginBottom:22}}><div><span className="eyebrow">MARGARYAN DISTRIBUTION / CRM</span><h1 style={{fontSize:42,margin:"8px 0 0"}}>Lead Pipeline</h1><p style={{color:"#8f96a3",maxWidth:720,lineHeight:1.55}}>One business record across research, outreach, replies, calls and meetings.</p></div><div style={{display:"flex",gap:8}}><a className="ghost" href="/autopilot" style={{textDecoration:"none"}}>Autopilot</a><a className="ghost" href="/" style={{textDecoration:"none"}}>Command</a></div></header>
 <section style={{...card,marginBottom:14,display:"grid",gridTemplateColumns:"1fr 220px auto",gap:10,alignItems:"center"}}><input style={control} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search company, name or email"/><select style={control} value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All stages</option>{["new","researched","contacted","replied","qualified","meeting","won","lost","do_not_contact"].map(value=><option key={value} value={value}>{value}</option>)}</select><button className="ghost" onClick={()=>void refresh()}>Refresh</button></section>
 <section style={card}><div className="panelHead"><div><span>PIPELINE</span><h3>Known business leads</h3></div><b>{filtered.length}</b></div><div style={{display:"grid",gap:8,marginTop:14}}>{filtered.length===0&&<div className="empty">No matching leads in this process.</div>}{filtered.map(lead=><a key={lead.id} href={`/leads/${lead.id}`} style={{display:"grid",gridTemplateColumns:"2fr 1fr 90px 1.4fr auto",gap:12,alignItems:"center",border:"1px solid #20242c",borderRadius:10,padding:14,textDecoration:"none",color:"inherit",background:"#0a0c0f"}}><div><strong>{lead.company}</strong><p style={{color:"#8f96a3",margin:"5px 0 0",fontSize:12}}>{lead.contactName||lead.role||lead.website||"Business lead"}</p></div><div><small>CONTACT</small><p style={{margin:"4px 0",fontSize:12}}>{lead.email||lead.phone||"research needed"}</p></div><strong style={{fontSize:22}}>{lead.score??"—"}</strong><div><span className={`pill ${["qualified","meeting","won"].includes(lead.stage)?"good":["lost","do_not_contact"].includes(lead.stage)?"bad":"wait"}`}>{lead.stage}</span>{lead.nextAction&&<p style={{fontSize:11,color:"#8f96a3",margin:"6px 0 0"}}>{lead.nextAction}</p>}</div><span>Open →</span></a>)}</div></section></main>;
}
