import OpenAI from "openai";
import {distributionStore} from "@/lib/store";

export type ExecutiveBrief={generatedAt:string;windowHours:number;headline:string;metrics:{newLeads:number;inboundReplies:number;positiveReplies:number;voiceCalls:number;meetingsAgreed:number;meetingsBooked:number;actionsSucceeded:number;approvalsNeeded:number;failures:number;deadLetters:number};wins:string[];attention:string[];conversations:Array<{company:string;channel:string;outcome:string;summary:string;nextAction?:string;nextActionAt?:string}>;nextMoves:string[]};

export async function buildExecutiveBrief(windowHours=24):Promise<ExecutiveBrief>{
  const hours=Math.max(1,Math.min(168,Math.round(windowHours)));const since=Date.now()-hours*3600000;const inWindow=(value?:string)=>Boolean(value&&Date.parse(value)>=since);const state=distributionStore.snapshot();
  const replies=state.replies.filter(x=>inWindow(x.receivedAt));const calls=state.calls.filter(x=>inWindow(x.completedAt||x.startedAt||x.createdAt));const meetings=state.meetings.filter(x=>inWindow(x.createdAt)||inWindow(x.updatedAt));const actions=state.actions.filter(x=>inWindow(x.executedAt||x.updatedAt||x.createdAt));const newLeads=state.leads.filter(lead=>{const mission=lead.missionId?state.missions.find(x=>x.id===lead.missionId):undefined;return mission?inWindow(mission.createdAt):false;});
  const company=(leadId?:string)=>state.leads.find(x=>x.id===leadId)?.company||"Unknown company";
  const conversations=[...replies.map(reply=>({company:company(reply.leadId),channel:"email",outcome:reply.decision.intent,summary:reply.decision.summary,nextAction:reply.decision.recommendedAction})),...calls.filter(x=>x.summary).map(call=>({company:company(call.leadId),channel:"voice",outcome:call.summary!.outcome,summary:call.summary!.summary,nextAction:call.summary!.nextAction,nextActionAt:call.summary!.nextActionAt}))].sort((a,b)=>(b.nextActionAt||"").localeCompare(a.nextActionAt||"")).slice(0,12);
  const approvals=state.actions.filter(x=>x.mode==="APPROVE"&&x.status==="queued");const failures=state.actions.filter(x=>["failed","blocked","dead_letter"].includes(x.status));const priorityLeads=state.leads.filter(x=>["replied","qualified","meeting"].includes(x.stage)&&x.nextAction).sort((a,b)=>Date.parse(a.nextActionAt||"9999-12-31")-Date.parse(b.nextActionAt||"9999-12-31"));
  const wins:string[]=[];for(const call of calls.filter(x=>x.summary?.outcome==="meeting"))wins.push(`${company(call.leadId)} agreed to a meeting.`);for(const meeting of meetings.filter(x=>x.status==="booked"))wins.push(`${company(meeting.leadId)} is booked for ${meeting.start}.`);for(const reply of replies.filter(x=>x.decision.intent==="positive"))wins.push(`${company(reply.leadId)} sent a positive email reply.`);
  const attention=[...approvals.slice(0,5).map(x=>`Approve: ${x.objective}`),...failures.slice(0,5).map(x=>`${x.status}: ${x.objective}${x.error?` — ${x.error}`:""}`)].slice(0,8);
  const nextMoves=priorityLeads.slice(0,5).map(x=>`${x.company}: ${x.nextAction}${x.nextActionAt?` by ${x.nextActionAt}`:""}`);if(!nextMoves.length&&approvals.length)nextMoves.push(`Review ${approvals.length} pending approval${approvals.length===1?"":"s"}.`);if(!nextMoves.length)nextMoves.push("No urgent human action is recorded in the current process state.");
  const metrics={newLeads:newLeads.length,inboundReplies:replies.length,positiveReplies:replies.filter(x=>x.decision.intent==="positive").length,voiceCalls:calls.length,meetingsAgreed:calls.filter(x=>x.summary?.outcome==="meeting").length,meetingsBooked:meetings.filter(x=>x.status==="booked").length,actionsSucceeded:actions.filter(x=>x.status==="succeeded").length,approvalsNeeded:approvals.length,failures:failures.filter(x=>x.status==="failed"||x.status==="blocked").length,deadLetters:failures.filter(x=>x.status==="dead_letter").length};
  let headline=`${metrics.positiveReplies} positive repl${metrics.positiveReplies===1?"y":"ies"}, ${metrics.meetingsAgreed} meeting${metrics.meetingsAgreed===1?"":"s"} agreed, ${metrics.approvalsNeeded} approval${metrics.approvalsNeeded===1?"":"s"} waiting.`;
  if(process.env.OPENAI_API_KEY){try{const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const response=await client.responses.create({model:process.env.OPENAI_PLANNER_MODEL||"gpt-5.6-terra",reasoning:{effort:"low"},instructions:"Write one terse executive headline, maximum 22 words. Use only supplied metrics; do not infer revenue, sentiment or outcomes not explicitly present.",input:JSON.stringify(metrics)});if(response.output_text.trim())headline=response.output_text.trim().replace(/^['\"]|['\"]$/g,"");}catch{}}
  return{generatedAt:new Date().toISOString(),windowHours:hours,headline,metrics,wins:wins.slice(0,8),attention,conversations,nextMoves};
}
