import {distributionStore} from "@/lib/store";

export type LeadTimelineEvent={id:string;at:string;type:"research"|"outreach"|"email_reply"|"call"|"meeting"|"action";channel:string;title:string;summary:string;status?:string;meta?:Record<string,unknown>};

export function buildLead360(leadId:string){
  const lead=distributionStore.getLead(leadId);if(!lead)throw new Error("Lead not found");
  const mission=lead.missionId?distributionStore.getMission(lead.missionId):undefined;const product=mission?.input.productId?distributionStore.getProduct(mission.input.productId):undefined;
  const events:LeadTimelineEvent[]=[];
  if(lead.research||lead.fitReason)events.push({id:`research-${lead.id}`,at:mission?.createdAt||new Date(0).toISOString(),type:"research",channel:"web",title:"Lead researched",summary:lead.research||lead.fitReason||"Research completed",status:lead.stage,meta:{score:lead.score,sourceUrls:lead.sourceUrls||[]}});
  for(const sequence of distributionStore.listOutreach().filter(x=>x.leadId===lead.id))events.push({id:`outreach-${sequence.id}`,at:sequence.createdAt,type:"outreach",channel:"multi",title:"Outreach sequence prepared",summary:`Initial email, follow-up, LinkedIn draft and call opening prepared in ${sequence.language.toUpperCase()}.`,meta:{sequenceId:sequence.id}});
  for(const action of distributionStore.listActions().filter(x=>x.payload.leadId===lead.id))events.push({id:`action-${action.recordId}`,at:action.executedAt||action.updatedAt||action.createdAt,type:"action",channel:action.channel,title:action.objective,summary:action.error||action.rationale,status:action.status,meta:{kind:action.kind,retryCount:action.retryCount,scheduledAt:action.scheduledAt,recordId:action.recordId}});
  for(const reply of distributionStore.listReplies().filter(x=>x.leadId===lead.id))events.push({id:`reply-${reply.id}`,at:reply.receivedAt,type:"email_reply",channel:"email",title:`Inbound: ${reply.decision.intent}`,summary:reply.decision.summary||reply.text.slice(0,300),status:reply.status,meta:{subject:reply.subject,recommendedAction:reply.decision.recommendedAction,urgency:reply.decision.urgency}});
  for(const call of distributionStore.listCalls().filter(x=>x.leadId===lead.id))events.push({id:`call-${call.id}`,at:call.completedAt||call.startedAt||call.createdAt,type:"call",channel:"voice",title:`Voice call: ${call.summary?.outcome||call.providerStatus||call.status}`,summary:call.summary?.summary||call.objective||"Voice call",status:call.status,meta:{callSid:call.callSid,nextAction:call.summary?.nextAction,nextActionAt:call.summary?.nextActionAt,needs:call.summary?.needs||[],objections:call.summary?.objections||[],commitments:call.summary?.commitments||[]}});
  for(const meeting of distributionStore.listMeetings().filter(x=>x.leadId===lead.id))events.push({id:`meeting-${meeting.id}`,at:meeting.start,type:"meeting",channel:"calendar",title:`Meeting: ${meeting.status}`,summary:`${meeting.title} · ${meeting.start} · ${meeting.timezone}`,status:meeting.status,meta:{meetingId:meeting.id,calendarHtmlLink:meeting.calendarHtmlLink,meetLink:meeting.meetLink,availabilityVerified:meeting.availabilityVerified}});
  events.sort((a,b)=>Date.parse(b.at)-Date.parse(a.at));
  const latestCall=distributionStore.listCalls().find(x=>x.leadId===lead.id&&x.summary);const latestReply=distributionStore.listReplies().find(x=>x.leadId===lead.id);const nextMeeting=distributionStore.listMeetings().filter(x=>x.leadId===lead.id&&x.status!=="cancelled"&&Date.parse(x.end)>Date.now()).sort((a,b)=>a.start.localeCompare(b.start))[0];
  const brief={headline:`${lead.company} · ${lead.stage.toUpperCase()}`,relationship:latestCall?.summary?.summary||latestReply?.decision.summary||lead.fitReason||lead.research||"No conversation evidence yet.",nextAction:lead.nextAction||latestCall?.summary?.nextAction||latestReply?.decision.recommendedAction||"Review lead",nextActionAt:lead.nextActionAt||latestCall?.summary?.nextActionAt,nextMeeting:nextMeeting?{id:nextMeeting.id,start:nextMeeting.start,status:nextMeeting.status,meetLink:nextMeeting.meetLink}:undefined,knownNeeds:latestCall?.summary?.needs||[],knownObjections:latestCall?.summary?.objections||[],commitments:latestCall?.summary?.commitments||[]};
  return{lead,mission,product,brief,events};
}
