import OpenAI from "openai";
import {distributionStore} from "@/lib/store";

const schema={type:"object",additionalProperties:false,required:["executiveSummary","whyTheyCare","knownNeeds","knownObjections","openQuestions","recommendedOpening","questionsToAsk","desiredOutcome","riskFlags"],properties:{executiveSummary:{type:"string"},whyTheyCare:{type:"string"},knownNeeds:{type:"array",items:{type:"string"}},knownObjections:{type:"array",items:{type:"string"}},openQuestions:{type:"array",items:{type:"string"}},recommendedOpening:{type:"string"},questionsToAsk:{type:"array",items:{type:"string"},minItems:3,maxItems:7},desiredOutcome:{type:"string"},riskFlags:{type:"array",items:{type:"string"}}}} as const;

export async function buildMeetingBrief(meetingId:string){
  const meeting=distributionStore.getMeeting(meetingId);if(!meeting)throw new Error("Meeting not found");const lead=distributionStore.getLead(meeting.leadId);if(!lead)throw new Error("Lead not found");const mission=distributionStore.getMission(meeting.missionId);const product=mission?.input.productId?distributionStore.getProduct(mission.input.productId):undefined;
  const replies=distributionStore.listReplies().filter(x=>x.leadId===lead.id).slice(0,8);const calls=distributionStore.listCalls().filter(x=>x.leadId===lead.id).slice(0,5);const context={meeting,lead,product:product?{name:product.name,oneLiner:product.oneLiner,pains:product.pains,proof:product.proof,objections:product.objections,useCases:product.useCases,forbiddenClaims:product.forbiddenClaims}:null,replies:replies.map(x=>({subject:x.subject,text:x.text,decision:x.decision})),calls:calls.map(x=>({summary:x.summary,transcript:x.transcript.slice(-30)}))};
  if(!process.env.OPENAI_API_KEY)return{executiveSummary:`${lead.company} · ${lead.research||lead.fitReason||"Known CRM lead"}`,whyTheyCare:lead.fitReason||"Validate the need during the meeting.",knownNeeds:calls.flatMap(x=>x.summary?.needs||[]),knownObjections:calls.flatMap(x=>x.summary?.objections||[]),openQuestions:["Who owns the decision?","What is the current workflow?","What would make a pilot worth doing?"],recommendedOpening:`Confirm the problem and the agreed purpose of this meeting before presenting ${product?.name||"the product"}.`,questionsToAsk:["What is happening today?","Where does the current process break?","Who else needs to be involved?","What would a successful pilot prove?"],desiredOutcome:"Agree one concrete next step, owner and date.",riskFlags:product?.forbiddenClaims||[]};
  const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const response=await client.responses.create({model:process.env.OPENAI_PLANNER_MODEL||"gpt-5.6-terra",reasoning:{effort:"medium"},instructions:["Create a terse B2B meeting-prep dossier for the human closer.","Use only supplied evidence. Never invent budget, authority, needs, objections, metrics or commitments.","Separate known facts from open questions.","Optimize for a 15-30 minute sales/demo conversation and one concrete next step.",`Write in ${lead.language==="ru"?"Russian":"English"}.`].join(" "),input:JSON.stringify(context),text:{format:{type:"json_schema",name:"meeting_brief",strict:true,schema}}});return JSON.parse(response.output_text);
}
