import OpenAI from "openai";
import type { ContentFormat, Language, MissionRecord, ProductRecord } from "@/lib/types";

export type SmmItem={channel:"x"|"linkedin"|"instagram";format:ContentFormat;scheduledOffsetHours:number;pillar:string;title:string;body:string;callToAction?:string;requiresMedia:boolean};

const itemSchema={type:"object",additionalProperties:false,required:["channel","format","scheduledOffsetHours","pillar","title","body","callToAction","requiresMedia"],properties:{channel:{type:"string",enum:["x","linkedin","instagram"]},format:{type:"string",enum:["post","thread","carousel","reel_script","story"]},scheduledOffsetHours:{type:"number",minimum:0,maximum:336},pillar:{type:"string"},title:{type:"string"},body:{type:"string"},callToAction:{type:"string"},requiresMedia:{type:"boolean"}}} as const;
const planSchema={type:"object",additionalProperties:false,required:["items"],properties:{items:{type:"array",minItems:6,maxItems:18,items:itemSchema}}} as const;

function fallbackCampaign(mission:MissionRecord,product?:ProductRecord):SmmItem[]{
 const ru=mission.input.language==="ru",name=product?.name||"the product",thesis=mission.plan.thesis,pillars=mission.plan.contentPillars.length?mission.plan.contentPillars:["Problem","Proof","Product","Founder perspective"];
 const copy=(en:string,rus:string)=>ru?rus:en;
 return [
  {channel:"x",format:"post",scheduledOffsetHours:1,pillar:pillars[0]||"Problem",title:copy("Problem insight","Наблюдение о проблеме"),body:copy(`${thesis}\n\nOne practical observation: the expensive part is often not the missing tool — it is the gap between a customer signal and a fast response.`,`${thesis}\n\nПрактическое наблюдение: дорого обходится не только отсутствие инструмента, а разрыв между сигналом клиента и быстрым ответом.`),callToAction:copy("What does this look like in your workflow?","Как это выглядит в вашем процессе?"),requiresMedia:false},
  {channel:"linkedin",format:"post",scheduledOffsetHours:5,pillar:pillars[0]||"Problem",title:copy("Operator perspective","Взгляд оператора"),body:copy(`A useful way to think about ${name}: start with the operational bottleneck, not with AI.\n\n${thesis}\n\nThen test one narrow workflow before expanding.`,`Полезный способ смотреть на ${name}: начинать не с ИИ, а с операционного узкого места.\n\n${thesis}\n\nСначала проверяем один узкий сценарий, потом расширяем.`),callToAction:copy("I can share the narrow pilot structure.","Могу показать структуру узкого пилота."),requiresMedia:false},
  {channel:"instagram",format:"reel_script",scheduledOffsetHours:24,pillar:pillars[1]||"Proof",title:copy("30-second proof script","30-секундный сценарий доказательства"),body:copy(`HOOK: Show the workflow before ${name}.\nSCENE 2: Show the handoff/problem.\nSCENE 3: Show the product flow.\nEND: One verified outcome or demo step only.`,`HOOK: Покажите процесс до ${name}.\nСЦЕНА 2: Покажите узкое место.\nСЦЕНА 3: Покажите работу продукта.\nФИНАЛ: Только один подтверждённый результат или шаг демо.`),callToAction:copy("See the workflow, not the hype.","Смотрите на процесс, а не на хайп."),requiresMedia:true},
  {channel:"x",format:"thread",scheduledOffsetHours:48,pillar:pillars[2]||"Product",title:copy("How it works thread","Тред: как это работает"),body:copy(`1/ The problem.\n2/ The workflow.\n3/ Where ${name} enters.\n4/ What stays human-controlled.\n5/ What to measure after deployment.`,`1/ Проблема.\n2/ Процесс.\n3/ Где подключается ${name}.\n4/ Что остаётся под контролем человека.\n5/ Что измерять после запуска.`),callToAction:copy("Reply if you want the checklist.","Ответьте, если нужен чек-лист."),requiresMedia:false},
  {channel:"linkedin",format:"post",scheduledOffsetHours:72,pillar:pillars[1]||"Proof",title:copy("Proof without fake metrics","Доказательства без выдуманных метрик"),body:copy(`Good distribution does not need inflated claims. For ${name}, we separate verified facts from hypotheses, show the actual workflow, and measure the delta after deployment.`,`Хорошей дистрибуции не нужны раздутые обещания. Для ${name} мы отделяем подтверждённые факты от гипотез, показываем реальный процесс и измеряем изменения после внедрения.`),callToAction:copy("Ask for the verification checklist.","Запросите чек-лист проверки."),requiresMedia:false},
  {channel:"instagram",format:"carousel",scheduledOffsetHours:96,pillar:pillars[2]||"Product",title:copy("5-slide workflow","Процесс в 5 слайдах"),body:copy(`Slide 1: the bottleneck.\nSlide 2: current process.\nSlide 3: ${name}.\nSlide 4: human control.\nSlide 5: what gets measured.`,`Слайд 1: узкое место.\nСлайд 2: текущий процесс.\nСлайд 3: ${name}.\nСлайд 4: контроль человека.\nСлайд 5: что измеряем.`),callToAction:copy("Save this workflow.","Сохраните этот процесс."),requiresMedia:true},
  {channel:"x",format:"post",scheduledOffsetHours:120,pillar:pillars[3]||"Founder perspective",title:copy("Founder note","Заметка основателя"),body:copy(`Building distribution around ${name} taught us something simple: frequency matters, but relevance matters more. One useful proof beats ten generic posts.`,`Работа над дистрибуцией ${name} показывает простую вещь: частота важна, но релевантность важнее. Одно полезное доказательство сильнее десяти общих постов.`),callToAction:"",requiresMedia:false},
  {channel:"linkedin",format:"post",scheduledOffsetHours:144,pillar:pillars[3]||"Founder perspective",title:copy("Week close","Итог недели"),body:copy(`This week’s distribution thesis for ${name}: educate on the problem, demonstrate the workflow, publish only verified proof, then move interested buyers into a direct conversation.`,`Тезис недели для ${name}: объяснить проблему, показать процесс, публиковать только подтверждённые доказательства, а заинтересованных переводить в прямой разговор.`),callToAction:copy("If this is your bottleneck, a short conversation is enough to test fit.","Если это ваше узкое место, короткого разговора достаточно, чтобы проверить fit."),requiresMedia:false}
 ];
}

export async function buildSmmCampaign(mission:MissionRecord,product?:ProductRecord,days=7):Promise<SmmItem[]>{
 const safeDays=Math.max(3,Math.min(14,Math.round(days)));
 if(!process.env.OPENAI_API_KEY)return fallbackCampaign(mission,product).filter(item=>item.scheduledOffsetHours<=safeDays*24);
 const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
 const response=await client.responses.create({model:process.env.OPENAI_CONTENT_MODEL||"gpt-5.6-luna",reasoning:{effort:"medium"},instructions:["You are the SMM planning layer of a B2B distribution OS.",`Build a ${safeDays}-day channel-native campaign across X, LinkedIn and Instagram.`,"Create 6-18 useful pieces, not filler. Repurpose themes across channels but rewrite natively for each network.","Use only supplied verified product facts. Never invent metrics, customers, awards, integrations or ROI.","LinkedIn should be operator/founder-grade, X concise and insight-led, Instagram visual-first with carousel/reel scripts when useful.","Set requiresMedia=true for carousel, reel_script or story formats that need visual assets.","Avoid engagement bait and spammy CTAs. Public brand actions will still require approval outside this planner."].join(" "),input:JSON.stringify({mission:mission.input,thesis:mission.plan.thesis,audience:mission.plan.audience,pillars:mission.plan.contentPillars,product:product||null,language:mission.input.language}),text:{format:{type:"json_schema",name:"smm_campaign",strict:true,schema:planSchema}}});
 const parsed=JSON.parse(response.output_text) as {items:SmmItem[]};return parsed.items.filter(item=>item.scheduledOffsetHours<=safeDays*24).slice(0,18);
}

export async function repurposeSource(args:{sourceText:string;language:Language;product?:ProductRecord}):Promise<SmmItem[]>{
 const text=args.sourceText.trim().slice(0,12000);if(!text)throw new Error("sourceText is required");
 if(!process.env.OPENAI_API_KEY){const fakeMission={input:{language:args.language},plan:{thesis:text.slice(0,240),contentPillars:["Source insight"]}} as unknown as MissionRecord;return fallbackCampaign(fakeMission,args.product).slice(0,4).map((item,index)=>({...item,scheduledOffsetHours:index}));}
 const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
 const response=await client.responses.create({model:process.env.OPENAI_CONTENT_MODEL||"gpt-5.6-luna",reasoning:{effort:"low"},instructions:["Repurpose one source into a channel-native B2B distribution pack.","Return 4-8 pieces across X, LinkedIn and Instagram, including at least one short-form visual script or carousel outline.","Preserve the source meaning. Do not add facts, metrics or claims absent from the source or verified product context.",`Write in ${args.language==="ru"?"Russian":"English"}.`].join(" "),input:JSON.stringify({source:text,product:args.product||null}),text:{format:{type:"json_schema",name:"repurpose_pack",strict:true,schema:planSchema}}});
 const parsed=JSON.parse(response.output_text) as {items:SmmItem[]};return parsed.items.slice(0,8).map((item,index)=>({...item,scheduledOffsetHours:index}));
}
