"use client";

import { useEffect, useMemo, useState } from "react";
import type { DashboardSnapshot } from "@/lib/types";

export default function InboxPage(){
 const [state,setState]=useState<DashboardSnapshot|null>(null);const [leadId,setLeadId]=useState("");const [subject,setSubject]=useState("Re: quick question");const [text,setText]=useState("Sounds interesting. Can you explain how this would work for us?");const [busy,setBusy]=useState<string|null>(null);const [notice,setNotice]=useState("Reply Intelligence processes only known CRM leads. Personal/unmatched inbox messages are ignored.");
 async function refresh(){const res=await fetch("/api/state",{cache:"no-store"});const data=await res.json() as DashboardSnapshot;setState(data);if(!leadId&&data.leads[0])setLeadId(data.leads[0].id);}
 useEffect(()=>{void refresh();},[]);
 const lead=useMemo(()=>state?.leads.find(item=>item.id===leadId),[state,leadId]);
 async function simulate(){if(!leadId||!text.trim())return;setBusy("simulate");try{const res=await fetch("/api/inbox/simulate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leadId,subject,text})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Simulation failed");setNotice(`Intent: ${data.result.reply.decision.intent}. Next action: ${data.result.reply.decision.recommendedAction}.`);await refresh();}catch(error){setNotice(error instanceof Error?error.message:"Simulation failed");}finally{setBusy(null);}}
 async function pollGmail(){setBusy("gmail");try{const res=await fetch("/api/inbox/gmail/poll",{method:"POST"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Gmail poll failed");setNotice(`Gmail: ${data.processed} known-lead replies processed; ${data.skippedUnknown} unrelated messages ignored.`);await refresh();}catch(error){setNotice(error instanceof Error?error.message:"Gmail poll failed");}finally{setBusy(null);}}
 const card={border:"1px solid #242831",background:"#0f1115",borderRadius:12,padding:18} as const;
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"36px 24px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,marginBottom:24}}><div><span className="eyebrow">MARGARYAN DISTRIBUTION / REPLY INTELLIGENCE</span><h1 style={{fontSize:42,margin:"8px 0 0"}}>Sales Inbox</h1></div><div style={{display:"flex",gap:8}}><button className="ghost" onClick={pollGmail} disabled={busy==="gmail"}>{busy==="gmail"?"Polling…":"Poll Gmail"}</button><a href="/" className="ghost" style={{textDecoration:"none"}}>← Command</a></div></header>
  <div className="notice"><span/> {notice}</div>
  <section style={{...card,marginBottom:14}}><div className="panelHead"><div><span>NO-CREDENTIAL TEST</span><h3>Simulate a real lead reply</h3></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:14}}><label><span style={{fontSize:9,color:"#777"}}>LEAD</span><select value={leadId} onChange={e=>setLeadId(e.target.value)} style={{display:"block",width:"100%",height:42,marginTop:6,background:"#0b0d10",color:"#eee",border:"1px solid #242831",borderRadius:8,padding:"0 10px"}}><option value="">Select lead</option>{(state?.leads||[]).map(item=><option key={item.id} value={item.id}>{item.company}{item.email?` · ${item.email}`:""}</option>)}</select></label><label><span style={{fontSize:9,color:"#777"}}>SUBJECT</span><input value={subject} onChange={e=>setSubject(e.target.value)} style={{display:"block",width:"100%",height:42,marginTop:6,background:"#0b0d10",color:"#eee",border:"1px solid #242831",borderRadius:8,padding:"0 10px"}}/></label></div><textarea value={text} onChange={e=>setText(e.target.value)} style={{width:"100%",minHeight:120,marginTop:10,background:"#0b0d10",color:"#eee",border:"1px solid #242831",borderRadius:8,padding:12,resize:"vertical"}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:10}}><span style={{fontSize:11,color:"#838a95"}}>{lead?`Stage: ${lead.stage} · next: ${lead.nextAction||"—"}`:"Select a lead"}</span><button className="ghost" onClick={simulate} disabled={!leadId||!text.trim()||busy==="simulate"}>{busy==="simulate"?"Analyzing…":"Simulate reply"}</button></div></section>
  <section style={card}><div className="panelHead"><div><span>INBOUND MEMORY</span><h3>{state?.replies.length||0} processed replies</h3></div></div><div style={{display:"flex",flexDirection:"column",marginTop:8}}>{(state?.replies||[]).length===0&&<div className="empty">No replies processed yet.</div>}{(state?.replies||[]).map(reply=>{const owner=state?.leads.find(item=>item.id===reply.leadId);return <article key={reply.id} style={{display:"grid",gridTemplateColumns:"130px minmax(0,1fr) 160px",gap:14,padding:"16px 6px",borderBottom:"1px solid #1b1e25",alignItems:"start"}}><div><span className={`pill ${reply.decision.intent==="positive"?"good":reply.decision.intent==="negative"||reply.decision.intent==="unsubscribe"?"bad":"wait"}`}>{reply.decision.intent}</span><div style={{fontSize:10,color:"#707783",marginTop:8}}>{Math.round(reply.decision.confidence*100)}% confidence</div></div><div><strong style={{fontSize:13}}>{owner?.company||reply.from}</strong><p style={{fontSize:12,color:"#969da7",lineHeight:1.5,margin:"6px 0"}}>{reply.decision.summary}</p><small style={{color:"#69717d"}}>{reply.subject}</small>{reply.decision.draftReply&&<div style={{marginTop:10,borderLeft:"2px solid #3b4230",paddingLeft:10,color:"#bbc1ca",fontSize:11,lineHeight:1.5}}>Draft: {reply.decision.draftReply}</div>}</div><div><span style={{fontSize:9,color:"#707783"}}>NEXT BEST ACTION</span><strong style={{display:"block",fontSize:12,marginTop:6,textTransform:"uppercase"}}>{reply.decision.recommendedAction}</strong><small style={{display:"block",color:"#777",marginTop:6}}>{reply.status}</small></div></article>})}</div></section>
 </main>;
}
