import type { ContentDraft, DashboardSnapshot, DistributionActionRecord, DistributionPlan, Lead, MissionInput, MissionRecord, OutreachSequence, PlannedAction, ProductRecord } from "@/lib/types";

type MemoryState={missions:MissionRecord[];actions:DistributionActionRecord[];content:ContentDraft[];leads:Lead[];products:ProductRecord[];outreach:OutreachSequence[]};
declare global { var __margaryanDistributionMemory: MemoryState | undefined; }
function state():MemoryState{if(!globalThis.__margaryanDistributionMemory)globalThis.__margaryanDistributionMemory={missions:[],actions:[],content:[],leads:[],products:[],outreach:[]};return globalThis.__margaryanDistributionMemory;}
function now(){return new Date().toISOString();}
function recordsFor(missionId:string,actions:PlannedAction[]):DistributionActionRecord[]{const createdAt=now();return actions.map(action=>({...action,recordId:crypto.randomUUID(),missionId,status:action.mode==="BLOCKED"?"blocked":"queued",scheduledAt:new Date(Date.now()+action.scheduledOffsetHours*3600000).toISOString(),createdAt,updatedAt:createdAt,retryCount:0}));}
export const memoryStore={
 createMission(input:MissionInput,plan:DistributionPlan){const createdAt=now();const mission:MissionRecord={id:crypto.randomUUID(),input,plan,status:"active",createdAt,updatedAt:createdAt};state().missions.unshift(mission);const actions=recordsFor(mission.id,plan.actions);state().actions.push(...actions);return{mission,actions};},
 getMission(id:string){return state().missions.find(x=>x.id===id);},listMissions(){return[...state().missions];},
 listActions(){return[...state().actions].sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt));},getAction(recordId:string){return state().actions.find(x=>x.recordId===recordId);},
 updateAction(recordId:string,patch:Partial<DistributionActionRecord>){const action=state().actions.find(x=>x.recordId===recordId);if(!action)return undefined;Object.assign(action,patch,{updatedAt:now()});return action;},
 addContent(drafts:Omit<ContentDraft,"id"|"createdAt">[]){const created=drafts.map(d=>({...d,id:crypto.randomUUID(),createdAt:now()}));state().content.unshift(...created);return created;},listContent(){return[...state().content];},
 addLeads(leads:Omit<Lead,"id">[]){const existing=new Set(state().leads.map(l=>`${l.company.toLowerCase()}|${(l.website||"").toLowerCase()}`));const created:Lead[]=[];for(const lead of leads){const key=`${lead.company.toLowerCase()}|${(lead.website||"").toLowerCase()}`;if(existing.has(key))continue;const item:Lead={...lead,id:crypto.randomUUID()};state().leads.unshift(item);existing.add(key);created.push(item);}return created;},listLeads(){return[...state().leads].sort((a,b)=>(b.score||0)-(a.score||0));},
 enqueueActions(missionId:string,actions:PlannedAction[]){const records=recordsFor(missionId,actions);state().actions.push(...records);return records;},
 addOutreach(sequence:Omit<OutreachSequence,"id"|"createdAt">){const item:OutreachSequence={...sequence,id:crypto.randomUUID(),createdAt:now()};state().outreach.unshift(item);return item;},listOutreach(){return[...state().outreach];},
 addProduct(product:Omit<ProductRecord,"id"|"createdAt"|"updatedAt">){const createdAt=now();const item:ProductRecord={...product,id:crypto.randomUUID(),createdAt,updatedAt:createdAt};state().products.unshift(item);return item;},listProducts(){return[...state().products];},getProduct(id:string){return state().products.find(x=>x.id===id);},
 snapshot():DashboardSnapshot{const missions=this.listMissions(),actions=this.listActions(),content=this.listContent(),leads=this.listLeads(),products=this.listProducts(),outreach=this.listOutreach();return{missions,actions,content,leads,products,outreach,stats:{activeMissions:missions.filter(x=>x.status==="active").length,queuedActions:actions.filter(x=>x.status==="queued"||x.status==="approved").length,approvalsNeeded:actions.filter(x=>x.mode==="APPROVE"&&x.status==="queued").length,completedActions:actions.filter(x=>x.status==="succeeded").length,researchedLeads:leads.length,products:products.length,outreachPrepared:outreach.length}};}
};
