import type { ContentDraft, DashboardSnapshot, DistributionActionRecord, DistributionPlan, InboundReply, Lead, LearningReport, MeetingRecord, MissionInput, MissionRecord, OutreachSequence, PerformanceEvent, PlannedAction, ProductRecord, VoiceCallRecord } from "@/lib/types";

type MemoryState={missions:MissionRecord[];actions:DistributionActionRecord[];content:ContentDraft[];leads:Lead[];products:ProductRecord[];outreach:OutreachSequence[];replies:InboundReply[];calls:VoiceCallRecord[];meetings:MeetingRecord[];performance:PerformanceEvent[];learnings:LearningReport[]};
declare global { var __margaryanDistributionMemory: MemoryState | undefined; }
function state():MemoryState{
  if(!globalThis.__margaryanDistributionMemory)globalThis.__margaryanDistributionMemory={missions:[],actions:[],content:[],leads:[],products:[],outreach:[],replies:[],calls:[],meetings:[],performance:[],learnings:[]};
  const current=globalThis.__margaryanDistributionMemory;current.calls??=[];current.meetings??=[];current.performance??=[];current.learnings??=[];return current;
}
function now(){return new Date().toISOString();}
function recordsFor(missionId:string,actions:PlannedAction[]):DistributionActionRecord[]{const createdAt=now();return actions.map(action=>({...action,recordId:crypto.randomUUID(),missionId,status:action.mode==="BLOCKED"?"blocked":"queued",scheduledAt:new Date(Date.now()+action.scheduledOffsetHours*3600000).toISOString(),createdAt,updatedAt:createdAt,retryCount:0}));}
function normalizeEmail(value:string){return value.trim().toLowerCase();}
export const memoryStore={
 createMission(input:MissionInput,plan:DistributionPlan){const createdAt=now();const mission:MissionRecord={id:crypto.randomUUID(),input,plan,status:"active",createdAt,updatedAt:createdAt};state().missions.unshift(mission);const actions=recordsFor(mission.id,plan.actions);state().actions.push(...actions);return{mission,actions};},
 getMission(id:string){return state().missions.find(x=>x.id===id);},listMissions(){return[...state().missions];},
 listActions(){return[...state().actions].sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt));},getAction(recordId:string){return state().actions.find(x=>x.recordId===recordId);},
 updateAction(recordId:string,patch:Partial<DistributionActionRecord>){const action=state().actions.find(x=>x.recordId===recordId);if(!action)return undefined;Object.assign(action,patch,{updatedAt:now()});return action;},
 stopPendingLeadActions(leadId:string,reason:string){const stopped:DistributionActionRecord[]=[];for(const action of state().actions){if(action.payload.leadId!==leadId)continue;if(!["queued","approved"].includes(action.status))continue;action.status="rejected";action.error=reason;action.rejectedAt=now();action.updatedAt=now();stopped.push(action);}return stopped;},
 addContent(drafts:Omit<ContentDraft,"id"|"createdAt">[]){const created=drafts.map(d=>({...d,id:crypto.randomUUID(),createdAt:now()}));state().content.unshift(...created);return created;},listContent(){return[...state().content];},getContent(id:string){return state().content.find(x=>x.id===id);},updateContent(id:string,patch:Partial<ContentDraft>){const item=state().content.find(x=>x.id===id);if(!item)return undefined;Object.assign(item,patch);return item;},
 addLeads(leads:Omit<Lead,"id">[]){const existing=new Set(state().leads.map(l=>`${l.company.toLowerCase()}|${(l.website||"").toLowerCase()}`));const created:Lead[]=[];for(const lead of leads){const key=`${lead.company.toLowerCase()}|${(lead.website||"").toLowerCase()}`;if(existing.has(key))continue;const item:Lead={...lead,id:crypto.randomUUID()};state().leads.unshift(item);existing.add(key);created.push(item);}return created;},
 listLeads(){return[...state().leads].sort((a,b)=>(b.score||0)-(a.score||0));},getLead(id:string){return state().leads.find(x=>x.id===id);},findLeadByEmail(email:string){const target=normalizeEmail(email);return state().leads.find(x=>x.email&&normalizeEmail(x.email)===target);},
 updateLead(id:string,patch:Partial<Lead>){const lead=state().leads.find(x=>x.id===id);if(!lead)return undefined;Object.assign(lead,patch);return lead;},
 enqueueActions(missionId:string,actions:PlannedAction[]){const records=recordsFor(missionId,actions);state().actions.push(...records);return records;},
 addOutreach(sequence:Omit<OutreachSequence,"id"|"createdAt">){const item:OutreachSequence={...sequence,id:crypto.randomUUID(),createdAt:now()};state().outreach.unshift(item);return item;},listOutreach(){return[...state().outreach];},
 addReply(reply:Omit<InboundReply,"id"|"createdAt">){const existing=state().replies.find(x=>x.externalId===reply.externalId);if(existing)return existing;const item:InboundReply={...reply,id:crypto.randomUUID(),createdAt:now()};state().replies.unshift(item);return item;},hasReplyExternalId(externalId:string){return state().replies.some(x=>x.externalId===externalId);},listReplies(){return[...state().replies].sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt));},
 upsertCall(call:Omit<VoiceCallRecord,"id"|"createdAt"|"updatedAt">){const existing=state().calls.find(x=>x.callSid===call.callSid);const updatedAt=now();if(existing){Object.assign(existing,call,{updatedAt});return existing;}const item:VoiceCallRecord={...call,id:crypto.randomUUID(),createdAt:updatedAt,updatedAt};state().calls.unshift(item);return item;},
 getCallBySid(callSid:string){return state().calls.find(x=>x.callSid===callSid);},updateCallBySid(callSid:string,patch:Partial<VoiceCallRecord>){const call=state().calls.find(x=>x.callSid===callSid);if(!call)return undefined;Object.assign(call,patch,{updatedAt:now()});return call;},listCalls(){return[...state().calls].sort((a,b)=>(b.completedAt||b.startedAt||b.createdAt).localeCompare(a.completedAt||a.startedAt||a.createdAt));},
 addMeeting(meeting:Omit<MeetingRecord,"id"|"createdAt"|"updatedAt">){const duplicate=meeting.sourceCallSid?state().meetings.find(x=>x.sourceCallSid===meeting.sourceCallSid):undefined;if(duplicate)return duplicate;const createdAt=now();const item:MeetingRecord={...meeting,id:crypto.randomUUID(),createdAt,updatedAt:createdAt};state().meetings.unshift(item);return item;},
 getMeeting(id:string){return state().meetings.find(x=>x.id===id);},updateMeeting(id:string,patch:Partial<MeetingRecord>){const item=state().meetings.find(x=>x.id===id);if(!item)return undefined;Object.assign(item,patch,{updatedAt:now()});return item;},listMeetings(){return[...state().meetings].sort((a,b)=>a.start.localeCompare(b.start));},
 addProduct(product:Omit<ProductRecord,"id"|"createdAt"|"updatedAt">){const createdAt=now();const item:ProductRecord={...product,id:crypto.randomUUID(),createdAt,updatedAt:createdAt};state().products.unshift(item);return item;},listProducts(){return[...state().products];},getProduct(id:string){return state().products.find(x=>x.id===id);},
 addPerformance(event:Omit<PerformanceEvent,"id"|"createdAt">){const item:PerformanceEvent={...event,id:crypto.randomUUID(),createdAt:now()};state().performance.unshift(item);return item;},listPerformance(){return[...state().performance].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));},
 addLearning(report:Omit<LearningReport,"id"|"generatedAt">){const item:LearningReport={...report,id:crypto.randomUUID(),generatedAt:now()};state().learnings.unshift(item);return item;},listLearnings(){return[...state().learnings].sort((a,b)=>b.generatedAt.localeCompare(a.generatedAt));},
 snapshot():DashboardSnapshot{const missions=this.listMissions(),actions=this.listActions(),content=this.listContent(),leads=this.listLeads(),products=this.listProducts(),outreach=this.listOutreach(),replies=this.listReplies(),calls=this.listCalls(),meetings=this.listMeetings(),performance=this.listPerformance(),learnings=this.listLearnings();return{missions,actions,content,leads,products,outreach,replies,calls,meetings,performance,learnings,stats:{activeMissions:missions.filter(x=>x.status==="active").length,queuedActions:actions.filter(x=>x.status==="queued"||x.status==="approved").length,approvalsNeeded:actions.filter(x=>x.mode==="APPROVE"&&x.status==="queued").length,completedActions:actions.filter(x=>x.status==="succeeded").length,researchedLeads:leads.length,products:products.length,outreachPrepared:outreach.length,inboundReplies:replies.length,positiveReplies:replies.filter(x=>x.decision.intent==="positive").length,voiceCalls:calls.length,meetings:meetings.length,bookedMeetings:meetings.filter(x=>x.status==="booked").length,performanceEvents:performance.length,learningReports:learnings.length}};}
};
